### ISSUE TITLE
StringIndexOutOfBoundsException on Parser$Decoder.decodeString

### ISSUE THREAD

**Issue by marcello-marabita-mblabs** [socketio/socket.io-client-java#119]
Hi im using socket.io on Genymotion Emulator with Android 5.0.0.
My application uses proguard enable with following config:

-keep class com.github.nkzawa.*\* { _; }
-keep interface com.github.nkzawa._\* { *; }

Following was my exception when try to emit with socket:
java.lang.StringIndexOutOfBoundsException: length=1; index=48
            at java.lang.String.indexAndLength(String.java:500)
            at java.lang.String.charAt(String.java:494)
            at com.github.nkzawa.socketio.parser.Parser$Decoder.decodeString(Unknown Source)
            at com.github.nkzawa.socketio.parser.Parser$Decoder.add(Unknown Source)
            at com.github.nkzawa.socketio.client.Manager.ondata(Unknown Source)
            at com.github.nkzawa.socketio.client.Manager.access$1000(Unknown Source)
            at com.github.nkzawa.socketio.client.Manager$2.call(Unknown Source)
            at com.github.nkzawa.emitter.Emitter.emit(Unknown Source)
            at com.github.nkzawa.engineio.client.Socket.onPacket(Unknown Source)
            at com.github.nkzawa.engineio.client.Socket.access$900(Unknown Source)
            at com.github.nkzawa.engineio.client.Socket$5.call(Unknown Source)
            at com.github.nkzawa.emitter.Emitter.emit(Unknown Source)
            at com.github.nkzawa.engineio.client.Transport.onPacket(Unknown Source)
            at com.github.nkzawa.engineio.client.transports.Polling.access$700(Unknown Source)
            at com.github.nkzawa.engineio.client.transports.Polling$2.call(Unknown Source)
            at com.github.nkzawa.engineio.parser.Parser.decodePayload(Unknown Source)
            at com.github.nkzawa.engineio.client.transports.Polling._onData(Unknown Source)
            at com.github.nkzawa.engineio.client.transports.Polling.onData(Unknown Source)
            at com.github.nkzawa.engineio.client.transports.PollingXHR$5$1.run(Unknown Source)
            at com.github.nkzawa.thread.EventThread$2.run(Unknown Source)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

The exceptions only occurs with minifyEnabled true (proguard enabled)
Someone have any idea about this? can be only a bug in emulator?

**Comment by ZaLeXemre** [comment]
I am getting the same error on GenyMotion when testing the release version (minifyenabled version). So I guess, it is be the emulator.

**Comment by andreidiaconu** [comment]
I am getting the same error, also on Genymotion, also with proguard enabled.

**Comment by shuoli84** [comment]
@nkzawa What's your plan to fix this?
@andreidiaconu could you please paste some code here? Are you using your own model class? Have you add proguard rules for your model classes?

**Comment by ckarthikv** [comment]
I'm having the same issue on a real ASUS phone - Essentially Intel chipsets are crashing when Minify is enabled in the release version. Any solution to this?

**Comment by beydogan** [comment]
I'm also having same issue on Asus. Any possible solutions?

**Comment by ugurcany** [comment]
Have you found any solution for this? I am having the same issue on real device.

**Comment by adieldev82** [comment]
I had the same issue.
In my case i had a need to know my location so i used LocationManager method:

              `  locationManager.requestSingleUpdate(LocationManager.GPS_PROVIDER, this, null);
                locationManager.requestSingleUpdate(LocationManager.NETWORK_PROVIDER, this, null);`

that cause the crash.
after debugging i figured out that  my app was crashed after executing  the LocationManager method:

`private void requestLocationUpdates(LocationRequest request, LocationListener listener,
            Looper looper, PendingIntent intent) {

        String packageName = mContext.getPackageName();

        // wrap the listener class
        ListenerTransport transport = wrapListener(listener, looper);

        try {
            mService.requestLocationUpdates(request, transport, intent, packageName);
       } catch (RemoteException e) {
           Log.e(TAG, "RemoteException", e);
       }
    }

(i didnt catch the exception , the code go on to native code and crash)

**The way i solve the problem :**
Just separate the location calls 

`if(locationManager.isProviderEnabled(LocationManager.GPS_PROVIDER)) {
                locationManager.requestSingleUpdate(LocationManager.GPS_PROVIDER, this, null);
             //continue
            }else if (locationManager.isProviderEnabled(LocationManager.NETWORK_PROVIDER)){
                locationManager.requestSingleUpdate(LocationManager.NETWORK_PROVIDER, this, null);
//continue
                            }else{ 
//continue }` 
that solve the problem
`

**Comment by kuhnp** [comment]
Same issue on real device (Asus) with proguard, any solutions?

**Comment by a8453770** [comment]
I had the same issue.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
