### ISSUE TITLE
websocket doesn't work on proxy/some wifi/devices?

### ISSUE THREAD

**Issue by hamberluo** [socketio/socket.io-client-java#211]
```
Fatal Exception: java.lang.IllegalStateException
state: 4
com.squareup.okhttp.internal.http.HttpConnection.writeRequest (HttpConnection.java:171)
com.squareup.okhttp.internal.http.HttpTransport.writeRequestHeaders (HttpTransport.java:76)
```

**Comment by nkzawa** [comment]
How can we reproduce the issue?

**Comment by joy-jianqiang** [comment]
ihave got the same issue, but i do not know how to reproduce it

java.lang.IllegalStateException: state: 4
	at com.squareup.okhttp.internal.http.HttpConnection.writeRequest(HttpConnection.java:171)
	at com.squareup.okhttp.internal.http.HttpTransport.writeRequestHeaders(HttpTransport.java:76)
	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:756)
	at com.squareup.okhttp.Call.getResponse(Call.java:274)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:230)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:201)
	at com.squareup.okhttp.Call.access$100(Call.java:36)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:164)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)

**Comment by fatihsokmen** [comment]
Trying an alternative port might solve issue. Switching to port 443 especially with SSL may help.

**Comment by nkzawa** [comment]
Closed due to inactivity. Feel free to reopen.

**Comment by ronenab** [comment]
Happens to me a lot. 
Tried to find out the reason with no success so far... 
Fatal Exception: java.lang.IllegalStateException: state: 4
       at com.squareup.okhttp.internal.http.HttpConnection.writeRequest(Bringg:171)
       at com.squareup.okhttp.internal.http.HttpTransport.writeRequestHeaders(Bringg:76)
       at com.squareup.okhttp.internal.http.HttpEngine.readResponse(Bringg:745)
       at com.squareup.okhttp.Call.getResponse(Bringg:268)
       at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Bringg:224)
       at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Bringg:195)
       at com.squareup.okhttp.Call.access$100(Bringg:34)
       at com.squareup.okhttp.Call$AsyncCall.execute(Bringg:162)
       at com.squareup.okhttp.internal.NamedRunnable.run(Bringg:33)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

**Comment by jozuasijsling** [comment]
Seeing the same issue. So far only on Android 4.4.2.
