### ISSUE TITLE
java.lang.NoClassDefFoundError: com/squareup/okhttp/ws/WebSocketListener

### ISSUE THREAD

**Issue by saidBeekast** [socketio/socket.io-client-java#264]
When I try to connect to a server using the example given in the readme, I get : 

Exception in thread "EventThread" java.lang.NoClassDefFoundError: com/squareup/okhttp/ws/WebSocketListener
	at io.socket.engineio.client.Socket.createTransport(Socket.java:269)
	at io.socket.engineio.client.Socket.probe(Socket.java:317)
	at io.socket.engineio.client.Socket.onOpen(Socket.java:472)
	at io.socket.engineio.client.Socket.onHandshake(Socket.java:512)
	at io.socket.engineio.client.Socket.onPacket(Socket.java:486)
	at io.socket.engineio.client.Socket.access$900(Socket.java:30)
	at io.socket.engineio.client.Socket$5.call(Socket.java:300)
	at io.socket.emitter.Emitter.emit(Emitter.java:117)
	at io.socket.engineio.client.Transport.onPacket(Transport.java:129)
	at io.socket.engineio.client.transports.Polling.access$700(Polling.java:17)
	at io.socket.engineio.client.transports.Polling$2.call(Polling.java:124)
	at io.socket.engineio.parser.Parser.decodePayload(Parser.java:251)
	at io.socket.engineio.client.transports.Polling._onData(Polling.java:134)
	at io.socket.engineio.client.transports.Polling.onData(Polling.java:106)
	at io.socket.engineio.client.transports.PollingXHR$5$1.run(PollingXHR.java:113)
	at io.socket.thread.EventThread$2.run(EventThread.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.squareup.okhttp.ws.WebSocketListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more

Any workaround to fix it please?

Thanks,

SB

**Comment by nkzawa** [comment]
What version of okhttp-ws do you use? It seems the latest okhttp-ws has backward incompatible changes.

**Comment by saidBeekast** [comment]
I use okhttp 2.6.0. Which version I've to take?

**Comment by nkzawa** [comment]
Please use okhttp 2.5.0 for now.

**Comment by saidBeekast** [comment]
I tried with okhttp 2.5.0 but same result.
Can you share a simple java project that works?
Thanks a lot.
