### ISSUE TITLE
NoClassDefFoundError io.socket.client.IO$Options

### ISSUE THREAD

**Issue by sebaber** [socketio/socket.io-client-java#276]
Hi i have this issue when i want to use socket.io in my Android project:

01-27 04:36:36.459: E/AndroidRuntime(23760): FATAL EXCEPTION: main
01-27 04:36:36.459: E/AndroidRuntime(23760): java.lang.NoClassDefFoundError: io.socket.client.IO$Options
01-27 04:36:36.459: E/AndroidRuntime(23760): 	at myproject.socketio.ConnectorAsyncSocketIO.<init>(ConnectorAsyncSocketIO.java:49)
01-27 04:36:36.459: E/AndroidRuntime(23760): 	at myproject.android.AndroidLauncher.onCreate(AndroidLauncher.java:25)
01-27 04:36:36.459: E/AndroidRuntime(23760): 	at android.app.Activity.performCreate(Activity.java:5372)
01-27 04:36:36.459: E/AndroidRuntime(23760): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
01-27 04:36:36.459: E/AndroidRuntime(23760): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2257)
01-27 04:36:36.459: E/AndroidRuntime(23760): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2349)
01-27 04:36:36.459: E/AndroidRuntime(23760): 	at android.app.ActivityThread.access$700(ActivityThread.java:159)
01-27 04:36:36.459: E/AndroidRuntime(23760): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
01-27 04:36:36.459: E/AndroidRuntime(23760): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-27 04:36:36.459: E/AndroidRuntime(23760): 	at android.os.Looper.loop(Looper.java:176)
01-27 04:36:36.459: E/AndroidRuntime(23760): 	at android.app.ActivityThread.main(ActivityThread.java:5419)
01-27 04:36:36.459: E/AndroidRuntime(23760): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-27 04:36:36.459: E/AndroidRuntime(23760): 	at java.lang.reflect.Method.invoke(Method.java:525)
01-27 04:36:36.459: E/AndroidRuntime(23760): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
01-27 04:36:36.459: E/AndroidRuntime(23760): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
01-27 04:36:36.459: E/AndroidRuntime(23760): 	at dalvik.system.NativeStart.main(Native Method)

The line in the ConnectorAsyncSocketIO.java:49 is this:
-> opts = new IO.Options();

Someone have the same problem??? i change all version of jdk and nothing solve that.

**Comment by nkzawa** [comment]
How did you install the library? I recommend to use `gradle` or `maven`, and it should solve the problem.

**Comment by sebaber** [comment]
Problem solved! yes i use gradle to include dependencies but i dont know that i have to include that lib too:

compile 'org.json:json:20151123'

with this and that:

compile 'io.socket:socket.io-client:0.6.3'

works for me =)

**Comment by tkharishankar** [comment]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/github/nkzawa/socketio/client/IO;

Caused by: java.lang.ClassNotFoundException: Didn't find class "com.github.nkzawa.socketio.client.IO" on path: DexPathList[[zip file "/data/app/com.fetchr.driver.beta-2/base.apk"],nativeLibraryDirectories=[/data/app/com.fetchr.driver.beta-2/lib/arm64, /data/app/com.fetchr.driver.beta-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)


can any one help me here

**Comment by dafeige8** [comment]
04-19 15:27:49.650 14806-14806/com.mdp.moblie.visualizationdisplay E/EquipListDetailActivity: http://10.13.62.202:6001/CT_LIGHT_MACHINE
04-19 15:27:49.787 14806-15286/com.mdp.moblie.visualizationdisplay E/EventThread: Task threw exception
    java.lang.NoClassDefFoundError: io.socket.engineio.client.transports.WebSocket$2
        at io.socket.engineio.client.transports.WebSocket.doOpen(WebSocket.java:78)
        at io.socket.engineio.client.Transport$1.run(Transport.java:82)
        at io.socket.thread.EventThread.exec(EventThread.java:55)
        at io.socket.engineio.client.Transport.open(Transport.java:77)
        at io.socket.engineio.client.Socket.probe(Socket.java:472)
        at io.socket.engineio.client.Socket.onOpen(Socket.java:485)
        at io.socket.engineio.client.Socket.onHandshake(Socket.java:526)
        at io.socket.engineio.client.Socket.onPacket(Socket.java:499)
        at io.socket.engineio.client.Socket.access$1000(Socket.java:31)
        at io.socket.engineio.client.Socket$5.call(Socket.java:313)
        at io.socket.emitter.Emitter.emit(Emitter.java:117)
        at io.socket.engineio.client.Transport.onPacket(Transport.java:134)
        at io.socket.engineio.client.transports.Polling.access$700(Polling.java:17)
        at io.socket.engineio.client.transports.Polling$2.call(Polling.java:124)
        at io.socket.engineio.parser.Parser.decodePayload(Parser.java:251)
        at io.socket.engineio.client.transports.Polling._onData(Polling.java:134)
        at io.socket.engineio.client.transports.Polling.onData(Polling.java:106)
        at io.socket.engineio.client.transports.PollingXHR$5$1.run(PollingXHR.java:111)
        at io.socket.thread.EventThread$2.run(EventThread.java:80)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)

When I changed from "ws://10.13.62.202:6001/CT_LIGHT_MACHINE" to "http://10.13.62.202:6001/CT_LIGHT_MACHINE", has been submitted to the "Java. Lang. NoClassDefFoundError: IO. Socket. Engineio. Client. Transports. The WebSocket $2" mistakes, who can help me to answer it ? Thanks very much !!!
