### ISSUE TITLE
java.lang.IllegalStateException: Unable to take ownership of connection from okhttp when .connect fails.

### ISSUE THREAD

**Issue by shobhitpuri** [socketio/socket.io-client-java#294]
Hi

Thanks for the great library! We have an Android app using socket io and we're seeing a lot of crashes due to following exception:

```
Fatal Exception: java.lang.IllegalStateException: Unable to take ownership of connection.
   at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:157)
   at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:42)
   at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:102)
   at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:168)
   at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
   at java.lang.Thread.run(Thread.java:841)
```

This is coming from `okhttp` library being used in `socketio`. After I see lots of failed attempts to connect as shown in following logs, the above crash happens:

```
**11:35:45:579** : error: io.socket.engineio.client.EngineIOException: websocket error
Socket.EVENT_DISCONNECT: onDisconnectListener called: Socket disconnected.
 .... // Lot of same exceptions as below 
Socket.EVENT_DISCONNECT: onDisconnectListener called: Socket disconnected.
Socket.EVENT_CONNECT: Socket connection established...
io.socket.engineio.client.EngineIOException: xhr post error

Socket.EVENT_DISCONNECT: onDisconnectListener called: Socket disconnected.
Socket.EVENT_CONNECT: Socket connection established...
error: io.socket.engineio.client.EngineIOException: xhr poll error

Socket.EVENT_DISCONNECT: onDisconnectListener called: Socket disconnected.
io.socket.engineio.client.EngineIOException: xhr poll error

Socket.EVENT_DISCONNECT: onDisconnectListener called: Socket disconnected.
**11:47:46:355** io.socket.engineio.client.EngineIOException: xhr poll error
... 
```

Not sure of the error type event. We use the same error callback for `EVENT_ERROR`, `EVENT_CONNECT_ERROR`, `EVENT_CONNECT_TIMEOUT`, `EVENT_RECONNECT_ERROR`, `EVENT_RECONNECT_FAILED`. Although from the timestamps it seems like a timeout.

The version of library being used is: `io.socket:socket.io-client:0.6.2`.

Someone opened an [Issue with okhttp](https://github.com/square/okhttp/issues/2440) regarding this exception but not sure if it is an error on their side. Please let me know if you need more details.

**Comment by baltar** [comment]
We have the same problem, is this being looked into?

**Comment by Zorayda** [comment]
Yo también tengo este dilema:

E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                  Process: com.americanassist.afiliado, PID: 28081
                  java.lang.IllegalStateException: Unable to take ownership of connection.
                      at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:174)
                      at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:45)
                      at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:119)
                      at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:168)

Lo han solucionado?

**Comment by Sammy03** [comment]
Is there any resolution to this issue?

**Comment by jido2015** [comment]
I'm having same issue

**Comment by jido2015** [comment]
I suggest you check if there is good network every time before connecting to socket.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
