### ISSUE TITLE
RejectedExecutionException Occured in onMessage.

### ISSUE THREAD

**Issue by joshimohit** [socketio/socket.io-client-java#295]
We are getting following exception from our Obfuscated android Application :

Non-fatal Exception: java.util.concurrent.RejectedExecutionException: Task b.a.e.d@1ab979f rejected from java.util.concurrent.ThreadPoolExecutor@223c30ec[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
       at okhttp3.internal.ws.RealWebSocket$1.onMessage(Unknown Source)
       at okhttp3.internal.ws.WebSocketReader.readControlFrame(Unknown Source)
       at okhttp3.internal.ws.WebSocketReader.processNextFrame(Unknown Source)
       at okhttp3.internal.ws.RealWebSocket.readMessage(Unknown Source)
       at okhttp3.ws.WebSocketCall.create(Unknown Source)
       at okhttp3.ws.WebSocketCall.create(Unknown Source)
       at okhttp3.ws.WebSocketCall$1.onResponse(Unknown Source)
       at okhttp3.RealCall$AsyncCall.execute(Unknown Source)
       at okhttp3.internal.NamedRunnable.run(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

**Android Versions :** 4.1.2, 4.2.2, 5.0, 5.1, 6.0
**Server Version :** 1.4.5
**Android Socket Client version :** 0.7.0

**Comment by roma86** [comment]
Catch this too. @joshimohit have you any conclusion for this?

**Comment by joshimohit** [comment]
@roma86 : Nope. I was analyzing this issue from quiet a some time, but have no luck. maybe @nkzawa  can help ?

**Comment by joshimohit** [comment]
@roma86  @nkzawa but there is this : https://github.com/square/okhttp/issues/2455

**Comment by dave-r12** [comment]
@joshimohit do you have a non-obfuscated stack trace of this exception? I can't make sense of the one you posted. For example, 

```
at okhttp3.internal.ws.RealWebSocket$1.onMessage(Unknown Source)
at okhttp3.internal.ws.WebSocketReader.readControlFrame(Unknown Source)
```

In the source code, readControlFrame never calls onMessage.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
