### ISSUE TITLE
SocketTimeoutException failed to connect to... after 90000ms

### ISSUE THREAD

**Issue by laihuythinh** [socketio/socket.io-client-java#307]
sometimes, The app has a crash from socket-io, but i don't know how to fix/catch it, can you help me to fix it ?  @nkzawa 

```
Fatal Exception: java.lang.AssertionError: java.net.SocketTimeoutException: failed to connect to /52.30.76.101 (port 9292) after 90000ms
       at libcore.io.IoBridge.connect(IoBridge.java:117)
       at java.nio.SocketChannelImpl.connect(SocketChannelImpl.java:199)
       at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:210)
       at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.net.SocketTimeoutException: failed to connect to /52.30.76.101 (port 9292) after 90000ms
       at libcore.io.IoBridge.connectErrno(IoBridge.java:189)
       at libcore.io.IoBridge.connect(IoBridge.java:127)
       at libcore.io.IoBridge.connect(IoBridge.java:115)
       at java.nio.SocketChannelImpl.connect(SocketChannelImpl.java:199)
       at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:210)
       at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by rahulkhanna16** [comment]
did you get solution to this? @laihuythinh @nkzawa 
m also stuck with this

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
