### ISSUE TITLE
30 FPS socket receiving fails with Out of memory error

### ISSUE THREAD

**Issue by Durisvk** [socketio/socket.io-client-java#311]
When I use socket.io on node js server creating a render loop which is sending a message "render" to all clients 30 times per second the android application with largeHeap set to true fails after 15 seconds with Out of memory error which looks like this:

```
14 21:01:21.340 12844-18714/com.main.fishyio E/dalvikvm-heap: Out of memory on a 516182-byte allocation.
06-14 21:01:21.340 12844-18714/com.main.fishyio E/dalvikvm: Out of memory: Heap Size=130567KB, Allocated=116497KB, Limit=49152KB
06-14 21:01:21.340 12844-18714/com.main.fishyio E/dalvikvm: Extra info: Footprint=130567KB, Allowed Footprint=130567KB, Trimmed=0KB
06-14 21:01:21.470 12844-18714/com.main.fishyio E/AndroidRuntime_3_crash: crash in the same process: EventThread
06-14 21:01:21.470 12844-18714/com.main.fishyio E/AndroidRuntime_3_crash: java.lang.OutOfMemoryError: (Heap Size=130567KB, Allocated=116497KB)
06-14 21:01:21.470 12844-18714/com.main.fishyio E/AndroidRuntime_3_crash:     at java.lang.String.<init>(String.java:432)
06-14 21:01:21.470 12844-18714/com.main.fishyio E/AndroidRuntime_3_crash:     at java.lang.AbstractStringBuilder.toString(AbstractStringBuilder.java:642)
06-14 21:01:21.470 12844-18714/com.main.fishyio E/AndroidRuntime_3_crash:     at java.lang.StringBuilder.toString(StringBuilder.java:663)
06-14 21:01:21.470 12844-18714/com.main.fishyio E/AndroidRuntime_3_crash:     at java.util.Formatter.toString(Formatter.java:935)
06-14 21:01:21.470 12844-18714/com.main.fishyio E/AndroidRuntime_3_crash:     at java.lang.String.format(String.java:1998)
06-14 21:01:21.470 12844-18714/com.main.fishyio E/AndroidRuntime_3_crash:     at java.lang.String.format(String.java:1972)
06-14 21:01:21.470 12844-18714/com.main.fishyio E/AndroidRuntime_3_crash:     at com.github.nkzawa.socketio.parser.Parser$Decoder.decodeString(Parser.java:231)
06-14 21:01:21.470 12844-18714/com.main.fishyio E/AndroidRuntime_3_crash:     at com.github.nkzawa.socketio.parser.Parser$Decoder.add(Parser.java:148)
06-14 21:01:21.470 12844-18714/com.main.fishyio E/AndroidRuntime_3_crash:     at com.github.nkzawa.socketio.client.Manager.ondata(Manager.java:339)
06-14 21:01:21.470 12844-18714/com.main.fishyio E/AndroidRuntime_3_crash:     at com.github.nkzawa.socketio.client.Manager.access$1100(Manager.java:19)
06-14 21:01:21.470 12844-18714/com.main.fishyio E/AndroidRuntime_3_crash:     at com.github.nkzawa.socketio.client.Manager$2.call(Manager.java:312)
06-14 21:01:21.470 12844-18714/com.main.fishyio E/AndroidRuntime_3_crash:     at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
06-14 21:01:21.470 12844-18714/com.main.fishyio E/AndroidRuntime_3_crash:     at com.github.nkzawa.engineio.client.Socket.onPacket(Socket.java:482)
06-14 21:01:21.470 12844-18714/com.main.fishyio E/AndroidRuntime_3_crash:     at com.github.nkzawa.engineio.client.Socket.access$800(Socket.java:29)
06-14 21:01:21.470 12844-18714/com.main.fishyio E/AndroidRuntime_3_crash:     at com.github.nkzawa.engineio.client.Socket$5.call(Socket.java:285)
06-14 21:01:21.470 12844-18714/com.main.fishyio E/AndroidRuntime_3_crash:     at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
06-14 21:01:21.470 12844-18714/com.main.fishyio E/AndroidRuntime_3_crash:     at com.github.nkzawa.engineio.client.Transport.onPacket(Transport.java:121)
06-14 21:01:21.470 12844-18714/com.main.fishyio E/AndroidRuntime_3_crash:     at com.github.nkzawa.engineio.client.Transport.onData(Transport.java:113)
06-14 21:01:21.470 12844-18714/com.main.fishyio E/AndroidRuntime_3_crash:     at com.github.nkzawa.engineio.client.transports.WebSocket.access$100(WebSocket.java:19)
06-14 21:01:21.470 12844-18714/com.main.fishyio E/AndroidRuntime_3_crash:     at com.github.nkzawa.engineio.client.transports.WebSocket$1$3.run(WebSocket.java:74)
06-14 21:01:21.470 12844-18714/com.main.fishyio E/AndroidRuntime_3_crash:     at com.github.nkzawa.thread.EventThread$2.run(EventThread.java:75)
06-14 21:01:21.470 12844-18714/com.main.fishyio E/AndroidRuntime_3_crash:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
06-14 21:01:21.470 12844-18714/com.main.fishyio E/AndroidRuntime_3_crash:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
06-14 21:01:21.470 12844-18714/com.main.fishyio E/AndroidRuntime_3_crash:     at java.lang.Thread.run(Thread.java:864)
```

more information about the error you can find here: http://stackoverflow.com/questions/37819593/out-of-memory-socket-io-rendering-android-application

**Comment by darrachequesne** [comment]
For future readers:

It looks like a performance issue in the application, not Socket.IO.

Please reopen if needed.
