### ISSUE TITLE
getting WebsocketNotConnectedException exception after socket connected

### ISSUE THREAD

**Issue by ashishrajvanshi-kiwi** [socketio/socket.io-client-java#335]
Process: com.tsg.com.tsgchatclient, PID: 4508
                                                                         org.java_websocket.exceptions.WebsocketNotConnectedException
                                                                             at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:566)
                                                                             at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:543)
                                                                             at org.java_websocket.client.WebSocketClient.send(WebSocketClient.java:171)
                                                                             at com.github.nkzawa.engineio.client.transports.WebSocket$2.call(WebSocket.java:114)
                                                                             at com.github.nkzawa.engineio.parser.Parser.encodePacket(Parser.java:63)
                                                                             at com.github.nkzawa.engineio.parser.Parser.encodePacket(Parser.java:42)
                                                                             at com.github.nkzawa.engineio.client.transports.WebSocket.write(WebSocket.java:110)
                                                                             at com.github.nkzawa.engineio.client.Transport$3.run(Transport.java:98)
                                                                             at com.github.nkzawa.thread.EventThread.exec(EventThread.java:50)
                                                                             at com.github.nkzawa.engineio.client.Transport.send(Transport.java:94)
                                                                             at com.github.nkzawa.engineio.client.Socket$7.call(Socket.java:317)
                                                                             at com.github.nkzawa.emitter.Emitter$OnceListener.call(Emitter.java:164)
                                                                             at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
                                                                             at com.github.nkzawa.engineio.client.Transport.onOpen(Transport.java:109)
                                                                             at com.github.nkzawa.engineio.client.transports.WebSocket.access$000(WebSocket.java:19)
                                                                             at com.github.nkzawa.engineio.client.transports.WebSocket$1$1.run(WebSocket.java:56)
                                                                             at com.github.nkzawa.thread.EventThread$2.run(EventThread.java:75)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                             at java.lang.Thread.run(Thread.java:818)

**Comment by mlkmhd** [comment]
I also have this problem!

**Comment by gatosoftware** [comment]
Somebody found the solution of this problem?

**Comment by darrachequesne** [comment]
That should be fixed in latest version, please reopen if needed.
