### ISSUE TITLE
Support okhttp 3.4.1?

### ISSUE THREAD

**Issue by joshimohit** [socketio/socket.io-client-java#339]
Can you please update okhttp support for version 3.4.1 ?

**Comment by JoneWeng** [comment]
i also got the problem 

 java.lang.NoSuchMethodError: No virtual method callEnqueue(Lokhttp3/Call;Lokhttp3/Callback;Z)V in class Lokhttp3/internal/Internal; or its super classes (declaration of 'okhttp3.internal.Internal' appears in /data/app/com.ulong.live.player-1/base.apk)
                                                                           at okhttp3.ws.WebSocketCall.enqueue(WebSocketCall.java:108)
                                                                           at io.socket.engineio.client.transports.WebSocket.doOpen(WebSocket.java:73)

**Comment by NomenSvyat** [comment]
Add dependency
`compile group: 'com.squareup.okhttp3', name: 'okhttp-ws', version: '3.4.1'`

**Comment by nkzawa** [comment]
released 0.8.0 which supports okhttp-3.4.1.
