### ISSUE TITLE
Java NullPointerException.

### ISSUE THREAD

**Issue by hifall** [socketio/socket.io-client-java#348]
I am seeing this exception on line "mSocket.disconnect();":

```
public void connectToSocket(final String room) {
    LogCS.e("LOG", "Connecting to socket");
    if(mSocket != null) {
        mSocket.close();
        mSocket.disconnect();
        mSocket = null;
}
```

And here is the callstack:

```
E/LOG: Check for socket reconnect
E/LOG: Connecting to socket
E/LOG: Closing socket
W/dalvikvm: threadid=23: thread exiting with uncaught exception (group=0x41722d58)
E/AndroidRuntime: FATAL EXCEPTION: EventThread
Process: com.studio.myapp, PID: 22663
java.lang.NullPointerException
at com.studio.mymodule.managers.socket.SocketManager.connectToSocket(SocketManager.java:73)
at com.studio.mymodule.managers.socket.SocketManager.tryToReconnect(SocketManager.java:361)
at com.studio.mymodule.ChatActivity$32.onSocketFailed(ChatActivity.java:1378)
at com.studio.mymodule.managers.socket.SocketManager.socketFailedDialog(SocketManager.java:318)
at com.studio.mymodule.managers.socket.SocketManager$2.call(SocketManager.java:118)
at io.socket.emitter.Emitter.emit(Emitter.java:117)
at io.socket.client.Socket.access$601(Socket.java:19)
at io.socket.client.Socket$5.run(Socket.java:177)
at io.socket.thread.EventThread.exec(EventThread.java:50)
at io.socket.client.Socket.emit(Socket.java:173)
at io.socket.client.Manager.emitAll(Manager.java:156)
at io.socket.client.Manager.access$600(Manager.java:20)
at io.socket.client.Manager$1$3.call(Manager.java:286)
at io.socket.emitter.Emitter.emit(Emitter.java:117)
at io.socket.engineio.client.Socket.onError(Socket.java:765)
at io.socket.engineio.client.Socket.access$800(Socket.java:30)
at io.socket.engineio.client.Socket$4.call(Socket.java:304)
at io.socket.emitter.Emitter.emit(Emitter.java:117)
at io.socket.engineio.client.Transport.onError(Transport.java:65)
at io.socket.engineio.client.transports.PollingXHR.access$100(PollingXHR.java:18)
at io.socket.engineio.client.transports.PollingXHR$6$1.run(PollingXHR.java:126)
at io.socket.thread.EventThread$2.run(EventThread.java:75)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
```

Is SocketManager thread-safe?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
