### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException Unexpected char 0x633

### ISSUE THREAD

**Issue by rishabh876** [socketio/socket.io-client-java#353]
I am getting `Fatal Exception: java.lang.IllegalArgumentException
Unexpected char 0x641 at ۱۶ in device-name value: Lenovo A5500-HV فارسی توسط انجمن پارس جی اس ام`

I am using io.socket:socket.io-client:0.7.0 and have also tried 0.8.1.

Here is the complete stack trace:

```
Fatal Exception: java.lang.IllegalArgumentException: Unexpected char 0x641 at ۱۶ in device-name value: Lenovo A5500-HV فارسی توسط انجمن پارس جی اس ام
       at okhttp3.Headers$Builder.checkNameAndValue(Headers.java:283)
       at okhttp3.Headers$Builder.add(Headers.java:233)
       at okhttp3.Request$Builder.addHeader(Request.java:177)
       at io.socket.engineio.client.transports.WebSocket.doOpen(WebSocket.java:67)
       at io.socket.engineio.client.Transport$1.run(Transport.java:75)
       at io.socket.thread.EventThread.exec(EventThread.java:50)
       at io.socket.engineio.client.Transport.open(Transport.java:70)
       at io.socket.engineio.client.Socket$2.run(Socket.java:237)
       at io.socket.thread.EventThread.exec(EventThread.java:50)
       at io.socket.engineio.client.Socket.open(Socket.java:215)
       at io.socket.client.Manager$1.run(Manager.java:330)
       at io.socket.thread.EventThread.exec(EventThread.java:50)
       at io.socket.client.Manager.open(Manager.java:250)
       at io.socket.client.Manager.open(Manager.java:240)
       at io.socket.client.Socket$3.run(Socket.java:133)
       at io.socket.thread.EventThread$2.run(EventThread.java:75)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

This issue was in OkHttp library but I think this has been already fixed. Here is the pull request of the fix : https://github.com/square/okhttp/pull/2587

Is this library using update OkHttp library?

**Comment by darrachequesne** [comment]
Fixed by https://github.com/socketio/engine.io-client-java/commit/8016a5d7462f9379b4ad0f5660188c8626319ca6.
