### ISSUE TITLE
Getting error using websocket transport

### ISSUE THREAD

**Issue by env3d** [socketio/socket.io-client-java#360]
I have a Java SE app that is using socketIO to connect to a nodejs server.  When I use polling transport, everything is fine.  However, when I use websocket transport by providing the following options:

`IO.Options opt = new IO.Options();
        opt.transports = new String[]{WebSocket.NAME};
        opt.forceNew = true;
        sock = IO.socket(uri, opt);
`

I get the following error:
`
io.socket.engineio.client.EngineIOException: websocket error
    at io.socket.engineio.client.Transport.onError(Transport.java:64)
    at io.socket.engineio.client.transports.WebSocket.access$500(WebSocket.java:32)
    at io.socket.engineio.client.transports.WebSocket$1$5.run(WebSocket.java:139)
    at io.socket.thread.EventThread$2.run(EventThread.java:75)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ProtocolException: Control frames must be final.
    at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:123)
    at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:104)
    at okhttp3.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
    at okhttp3.ws.WebSocketCall.createWebSocket(WebSocketCall.java:152)
    at okhttp3.ws.WebSocketCall.access$000(WebSocketCall.java:41)
    at okhttp3.ws.WebSocketCall$1.onResponse(WebSocketCall.java:97)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:33)
    ... 3 more
`

Any ideas?

**Comment by Harekam** [comment]
@env3d any updates on this?

**Comment by env3d** [comment]
Nothing yet I'm afraid.  I do know that the library works well on Android.

**Comment by Harekam** [comment]
I found the solution there is an option called query in opt object
opt.query="transport=websocket"

This might work.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
