### ISSUE TITLE
android io.socket.engineio.client.EngineIOException: websocket error

### ISSUE THREAD

**Issue by Baifann** [socketio/socket.io-client-java#378]
I am trying use `engineio.client` in Android.Here is my code.
```java
        Socket.Options options = new Socket.Options();
        options.host = "127.0.0.1";
        options.transports = new String[]{WebSocket.NAME};
        options.port = 80;
        try {
//            mSocketServer = new Socket(url, opts);
            mSocketServer = new Socket(options);


            mSocketServer.on(Socket.EVENT_OPEN, new Emitter.Listener() {
                @Override
                public void call(Object... args) {
                    Log.i(TAG, "open");
                }
            });
            mSocketServer.on(Socket.EVENT_ERROR, new Emitter.Listener() {
                @Override
                public void call(Object... args) {
                    Exception err = (Exception) args[0];
                    Log.i(TAG, "error:" + err.toString());
                }
            });
            mSocketServer.on(Socket.EVENT_PACKET, new Emitter.Listener() {
                @Override
                public void call(Object... args) {
                    Log.i(TAG, "packet");
                }
            });

            mSocketServer.on(Socket.EVENT_DRAIN, new Emitter.Listener() {
                @Override
                public void call(Object... args) {
                    Log.i(TAG, "drain");
                }
            });
            mSocketServer.open();
            Log.i(TAG, "open...");

        } catch (Exception e) {
            e.printStackTrace();
        }
```
But result is error.The log is here
```
io.socket.engineio.client.EngineIOException: websocket error
12-21 06:39:10.922 32660-1780/com.example.baifan.iosocketdemo I/System.out: 	at io.socket.engineio.client.Transport.onError(Transport.java:71) ~[na:0.0]
12-21 06:39:10.923 32660-1780/com.example.baifan.iosocketdemo I/System.out: 	at io.socket.engineio.client.transports.WebSocket.access$500(WebSocket.java:28) ~[na:0.0]
12-21 06:39:10.923 32660-1780/com.example.baifan.iosocketdemo I/System.out: 	at io.socket.engineio.client.transports.WebSocket$2$5.run(WebSocket.java:150) ~[na:0.0]
12-21 06:39:10.923 32660-1780/com.example.baifan.iosocketdemo I/System.out: 	at io.socket.thread.EventThread$2.run(EventThread.java:80) ~[na:0.0]
12-21 06:39:10.923 32660-1780/com.example.baifan.iosocketdemo I/System.out: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) ~[na:0.0]
12-21 06:39:10.923 32660-1780/com.example.baifan.iosocketdemo I/System.out: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) ~[na:0.0]
12-21 06:39:10.923 32660-1780/com.example.baifan.iosocketdemo I/System.out: 	at java.lang.Thread.run(Thread.java:841) ~[na:0.0]
12-21 06:39:10.924 32660-1780/com.example.baifan.iosocketdemo I/System.out: Caused by: java.net.ConnectException: Failed to connect to /127.0.0.1:80
12-21 06:39:10.924 32660-1780/com.example.baifan.iosocketdemo I/System.out: 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:189) ~[na:0.0]
12-21 06:39:10.924 32660-1780/com.example.baifan.iosocketdemo I/System.out: 	at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:173) ~[na:0.0]
12-21 06:39:10.924 32660-1780/com.example.baifan.iosocketdemo I/System.out: 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114) ~[na:0.0]
12-21 06:39:10.924 32660-1780/com.example.baifan.iosocketdemo I/System.out: 	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193) ~[na:0.0]
12-21 06:39:10.924 32660-1780/com.example.baifan.iosocketdemo I/System.out: 	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129) ~[na:0.0]
12-21 06:39:10.925 32660-1780/com.example.baifan.iosocketdemo I/System.out: 	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98) ~[na:0.0]
12-21 06:39:10.925 32660-1780/com.example.baifan.iosocketdemo I/System.out: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) ~[na:0.0]
12-21 06:39:10.925 32660-1780/com.example.baifan.iosocketdemo I/System.out: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[na:0.0]
12-21 06:39:10.925 32660-1780/com.example.baifan.iosocketdemo I/System.out: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[na:0.0]
12-21 06:39:10.925 32660-1780/com.example.baifan.iosocketdemo I/System.out: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109) ~[na:0.0]
12-21 06:39:10.925 32660-1780/com.example.baifan.iosocketdemo I/System.out: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[na:0.0]
12-21 06:39:10.926 32660-1780/com.example.baifan.iosocketdemo I/System.out: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[na:0.0]
12-21 06:39:10.926 32660-1780/com.example.baifan.iosocketdemo I/System.out: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[na:0.0]
12-21 06:39:10.926 32660-1780/com.example.baifan.iosocketdemo I/System.out: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[na:0.0]
12-21 06:39:10.926 32660-1780/com.example.baifan.iosocketdemo I/System.out: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124) ~[na:0.0]
12-21 06:39:10.926 32660-1780/com.example.baifan.iosocketdemo I/System.out: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[na:0.0]
12-21 06:39:10.926 32660-1780/com.example.baifan.iosocketdemo I/System.out: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[na:0.0]
12-21 06:39:10.926 32660-1780/com.example.baifan.iosocketdemo I/System.out: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170) ~[na:0.0]
12-21 06:39:10.927 32660-1780/com.example.baifan.iosocketdemo I/System.out: 	at okhttp3.RealCall.access$100(RealCall.java:33) ~[na:0.0]
12-21 06:39:10.927 32660-1780/com.example.baifan.iosocketdemo I/System.out: 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120) ~[na:0.0]
12-21 06:39:10.927 32660-1780/com.example.baifan.iosocketdemo I/System.out: 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) ~[na:0.0]
```

**Comment by b95505017** [comment]
If there is an exception related to `io.socket.engineio` you should file the issue to [engine.io-client-java](https://github.com/socketio/engine.io-client-java).

Did you try a real server other than `127.0.0.1:80`?

**Comment by Baifann** [comment]
Sorry about that.It's my false.Your code is right.I change ip address everthing is ok.
