### ISSUE TITLE
Error in Java Project - imported JAR

### ISSUE THREAD

**Issue by aradhell** [socketio/socket.io-client-java#38]
Hi,
 I imported jar files (socketio and engineio) from Maven to eclipse project lib but it gives no class def found error. i checked both of them on build path / export.

http://mvnrepository.com/artifact/com.github.nkzawa/socket.io-client/0.1.3
http://mvnrepository.com/artifact/com.github.nkzawa/engine.io-client/0.2.3

Exception in thread "main" java.lang.NoClassDefFoundError: org/json/JSONException
    at com.github.nkzawa.socketio.client.Manager.<init>(Manager.java:143)
    at com.github.nkzawa.socketio.client.IO.socket(IO.java:73)
    at com.github.nkzawa.socketio.client.IO.socket(IO.java:37)
    at com.github.nkzawa.socketio.client.IO.socket(IO.java:33)
    at com.xx.deneme.MainW.<init>(MainW.java:74)
    at com.xx.deneme.MainW.main(MainW.java:63)
Caused by: java.lang.ClassNotFoundException: org.json.JSONException
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 6 more

**Comment by the7erm** [comment]
For the record, you'll also need: https://github.com/socketio/engine.io-client-java
```
Exception in thread "main" java.lang.NoClassDefFoundError: io/socket/engineio/client/Socket$Options
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at TestClient.main(TestClient.java:20)
Caused by: java.lang.ClassNotFoundException: io.socket.engineio.client.Socket$Options
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

```
