### ISSUE TITLE
Some error on Transport

### ISSUE THREAD

**Issue by 88567free** [socketio/socket.io-client-java#390]
java.lang.NullPointerException: value == null
	at okhttp3.q$a.d(SourceFile:316)
	at okhttp3.q$a.a(SourceFile:270)
	at okhttp3.w$a.b(SourceFile:175)
	at io.socket.engineio.client.a.c.e(SourceFile:67)
	at io.socket.engineio.client.Transport$1.run(SourceFile:75)
	at io.socket.g.a.a(SourceFile:50)
	at io.socket.engineio.client.Transport.a(SourceFile:70)
	at io.socket.engineio.client.Socket.e(SourceFile:458)
	at io.socket.engineio.client.Socket.f(SourceFile:471)
	at io.socket.engineio.client.Socket.a(SourceFile:512)
	at io.socket.engineio.client.Socket.a(SourceFile:485)
	at io.socket.engineio.client.Socket.a(SourceFile:30)
	at io.socket.engineio.client.Socket$17.a(SourceFile:299)
	at io.socket.b.a.a(SourceFile:117)
	at io.socket.engineio.client.Transport.a(SourceFile:127)
	at io.socket.engineio.client.a.a.a(SourceFile:17)
	at io.socket.engineio.client.a.a$2.a(SourceFile:124)
	at io.socket.engineio.parser.c.a(SourceFile:251)
	at io.socket.engineio.client.a.a.a(SourceFile:134)
	at io.socket.engineio.client.a.a.a(SourceFile:106)
	at io.socket.engineio.client.a.b$5$1.run(SourceFile:113)
	at io.socket.g.a$2.run(SourceFile:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:848)

anyone has same error？ how to solve！

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
