### ISSUE TITLE
Conflict with okHttp3

### ISSUE THREAD

**Issue by leodeleon22** [socketio/socket.io-client-java#391]
I'm using ht following dependencies 

`compile('io.socket:socket.io-client:0.8.2') {
        exclude group: 'org.json', module: 'json'
    }
    compile 'com.squareup.okhttp3:okhttp:3.6.0'
    compile 'com.squareup.retrofit2:retrofit:2.1.0'`

But I get this error not one but 3 times

`FATAL EXCEPTION: EventThread
                                                                Process: appli.speaky.com, PID: 1644
                                                                java.lang.NoSuchMethodError: No virtual method setCallWebSocket(Lokhttp3/Call;)V in class Lokhttp3/internal/Internal; or its super classes (declaration of 'okhttp3.internal.Internal' appears in /data/data/appli.example.com/files/instant-run/dex/slice-okhttp-3.6.0_29bb10e5f590229716bfa8daf196d09ea67f56a8-classes.dex)
                                                                    at okhttp3.ws.WebSocketCall.enqueue(WebSocketCall.java:108)
                                                                    at io.socket.engineio.client.transports.WebSocket.doOpen(WebSocket.java:84)
                                                                    at io.socket.engineio.client.Transport$1.run(Transport.java:82)
                                                                    at io.socket.thread.EventThread.exec(EventThread.java:55)
                                                                    at io.socket.engineio.client.Transport.open(Transport.java:77)
                                                                    at io.socket.engineio.client.Socket.probe(Socket.java:472)
                                                                    at io.socket.engineio.client.Socket.onOpen(Socket.java:485)
                                                                    at io.socket.engineio.client.Socket.onHandshake(Socket.java:526)
                                                                    at io.socket.engineio.client.Socket.onPacket(Socket.java:499)
                                                                    at io.socket.engineio.client.Socket.access$1000(Socket.java:31)
                                                                    at io.socket.engineio.client.Socket$5.call(Socket.java:313)
                                                                    at io.socket.emitter.Emitter.emit(Emitter.java:117)
                                                                    at io.socket.engineio.client.Transport.onPacket(Transport.java:134)
                                                                    at io.socket.engineio.client.transports.Polling.access$700(Polling.java:17)
                                                                    at io.socket.engineio.client.transports.Polling$2.call(Polling.java:124)
                                                                    at io.socket.engineio.parser.Parser.decodePayload(Parser.java:251)
                                                                    at io.socket.engineio.client.transports.Polling._onData(Polling.java:134)
                                                                    at io.socket.engineio.client.transports.Polling.onData(Polling.java:106)
                                                                    at io.socket.engineio.client.transports.PollingXHR$5$1.run(PollingXHR.java:111)
                                                                    at io.socket.thread.EventThread$2.run(EventThread.java:80)
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                    at java.lang.Thread.run(Thread.java:761)`

**Comment by leodeleon22** [comment]
Using version 0.8.3 corrects the problem
