### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'okio.BufferedSource okhttp3.ResponseBody.source()' on a null object reference

### ISSUE THREAD

**Issue by MissBears** [socketio/socket.io-client-java#410]
java.lang.NullPointerException: Attempt to invoke virtual method 'okio.BufferedSource okhttp3.ResponseBody.source()' on a null object reference
	at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:103)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:124)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
	at okhttp3.RealCall.e(SourceFile:170)
	at okhttp3.RealCall.a(SourceFile:33)
	at okhttp3.RealCall$AsyncCall.execute(SourceFile:120)
	at okhttp3.internal.NamedRunnable.run(SourceFile:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

my app accurd this problem sometimes.

**Comment by MissBears** [comment]
can you help me to resolve this bug

**Comment by b95505017** [comment]
How to reproduce this issue? I didn't see the code stack related to socket.io.
