### ISSUE TITLE
Problem using transport

### ISSUE THREAD

**Issue by wazodevs** [socketio/socket.io-client-java#420]
Hi guys i am trying to use Socket.io and I'm having problem to implement it... I connect to my https adress with socket. But when i am trying to set up the Transport, Android studio sends to me an error 

 ```
mSocket.io().on(Manager.EVENT_TRANSPORT, new Emitter.Listener() {
                            @Override
                            public void call(Object... args) {
                                Transport transport = (Transport)args[0];

                                transport.on(Transport.EVENT_REQUEST_HEADERS, new Emitter.Listener() {
                                    @Override
                                    public void call(Object... args) {
                                        @SuppressWarnings("unchecked")
                                        Map<String, List<String>> headers = (Map<String, List<String>>)args[0];
                                        // modify request headers
                                        headers.put("Cookie", Arrays.asList("foo=1;"));
                                    }
                                });

                                transport.on(Transport.EVENT_RESPONSE_HEADERS, new Emitter.Listener() {
                                    @Override
                                    public void call(Object... args) {
                                        @SuppressWarnings("unchecked")
                                        Map<String, List<String>> headers = (Map<String, List<String>>)args[0];
                                        // access response headers
                                        String cookie = headers.get("Set-Cookie").get(0);
                                    }
                                });
                            }
                        });
                      mSocket.on(Socket.EVENT_CONNECT, new Emitter.Listener() {

                            @Override
                            public void call(Object... args) {
                            }

                        });
```

This is the error throwed.

E/EventThread: Task threw exception
               java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
                   at io.socket.engineio.client.transports.PollingXHR$Request.create(PollingXHR.java:193)
                   at io.socket.engineio.client.transports.PollingXHR.doPoll(PollingXHR.java:129)
                   at io.socket.engineio.client.transports.Polling.poll(Polling.java:95)
                   at io.socket.engineio.client.transports.Polling.doOpen(Polling.java:35)
                   at io.socket.engineio.client.Transport$1.run(Transport.java:82)
                   at io.socket.thread.EventThread.exec(EventThread.java:55)
                   at io.socket.engineio.client.Transport.open(Transport.java:77)
                   at io.socket.engineio.client.Socket$2.run(Socket.java:248)
                   at io.socket.thread.EventThread.exec(EventThread.java:55)
                   at io.socket.engineio.client.Socket.open(Socket.java:226)
                   at io.socket.client.Manager$1.run(Manager.java:330)
                   at io.socket.thread.EventThread.exec(EventThread.java:55)
                   at io.socket.client.Manager.open(Manager.java:250)
                   at io.socket.client.Manager.open(Manager.java:240)
                   at io.socket.client.Socket$3.run(Socket.java:133)
                   at io.socket.thread.EventThread$2.run(EventThread.java:80)
                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                   at java.lang.Thread.run(Thread.java:818)

¿Any solution?
Thx 4 all

**Comment by darrachequesne** [comment]
For future readers:

That should be fixed in latest versions. Please reopen if needed.
