### ISSUE TITLE
Task threw exception - java.lang.InstantiationError When listening for events on Socket

### ISSUE THREAD

**Issue by passiondroid** [socketio/socket.io-client-java#426]
[ 8709-9205/com.ocharge E/EventThread: Task threw exception
                                                        java.lang.InstantiationError: okhttp3.internal.ws.RealWebSocket
                                                            at okhttp3.OkHttpClient.newWebSocket(OkHttpClient.java:404)
                                                            at io.socket.engineio.client.transports.WebSocket.doOpen(WebSocket.java:78)
                                                            at io.socket.engineio.client.Transport$1.run(Transport.java:82)
                                                            at io.socket.thread.EventThread.exec(EventThread.java:55)
                                                            at io.socket.engineio.client.Transport.open(Transport.java:77)
                                                            at io.socket.engineio.client.Socket.probe(Socket.java:472)
                                                            at io.socket.engineio.client.Socket.onOpen(Socket.java:485)
                                                            at io.socket.engineio.client.Socket.onHandshake(Socket.java:526)
                                                            at io.socket.engineio.client.Socket.onPacket(Socket.java:499)
                                                            at io.socket.engineio.client.Socket.access$1000(Socket.java:31)
                                                            at io.socket.engineio.client.Socket$5.call(Socket.java:313)
                                                            at io.socket.emitter.Emitter.emit(Emitter.java:117)
                                                            at io.socket.engineio.client.Transport.onPacket(Transport.java:134)
                                                            at io.socket.engineio.client.transports.Polling.access$700(Polling.java:17)
                                                            at io.socket.engineio.client.transports.Polling$2.call(Polling.java:124)
                                                            at io.socket.engineio.parser.Parser.decodePayload(Parser.java:188)
                                                            at io.socket.engineio.client.transports.Polling._onData(Polling.java:132)
                                                            at io.socket.engineio.client.transports.Polling.onData(Polling.java:101)
                                                            at io.socket.engineio.client.transports.PollingXHR$5$1.run(PollingXHR.java:109)
                                                            at io.socket.thread.EventThread$2.run(EventThread.java:80)
                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                            at java.lang.Thread.run(Thread.java:761)](url)

**Comment by amardeokar23** [comment]
The reason could be library conflict.
https://github.com/parse-community/ParseLiveQuery-Android/issues/68

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
