### ISSUE TITLE
Fatal Exception: java.lang.InternalError: Thread starting during runtime shutdown

### ISSUE THREAD

**Issue by alla2040** [socketio/socket.io-client-java#433]
I have this crash from many users of my app via Fabric:

Fatal Exception: java.lang.InternalError: Thread starting during runtime shutdown
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:921)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1328)
       at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:584)
       at io.socket.thread.EventThread.nextTick(EventThread.java:71)
       at io.socket.thread.EventThread.exec(EventThread.java:52)
       at io.socket.engineio.client.transports.WebSocket$1.onFailure(WebSocket.java:136)
       at okhttp3.internal.ws.RealWebSocket.readerErrorClose(RealWebSocket.java:217)
       at okhttp3.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:100)
       at okhttp3.ws.WebSocketCall.createWebSocket(WebSocketCall.java:152)
       at okhttp3.ws.WebSocketCall.access$000(WebSocketCall.java:41)
       at okhttp3.ws.WebSocketCall$1.onResponse(WebSocketCall.java:97)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:33)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

**Comment by Bluesir9** [comment]
I encountered the same crash as well although the stack trace is slightly different:

Fatal Exception: java.lang.InternalError: Thread starting during runtime shutdown
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:920)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1327)
       at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:583)
       at io.socket.thread.EventThread.nextTick(EventThread.java:76)
       at io.socket.thread.EventThread.exec(EventThread.java:57)
       at io.socket.client.Manager$1$4.run(Manager.java:326)
       at java.util.Timer$TimerImpl.run(Timer.java:284)

OS:Android
Socket IO Client version:1.0.0

**Comment by VeeraAnudeep** [comment]
Similar stack trace, GiONE F103 is the device, OS: Android 6 ,Socket IO Client version:0.8.3
Fatal Exception: java.lang.InternalError: Thread starting during runtime shutdown
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:921)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1328)
       at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:584)
       at io.socket.thread.EventThread.nextTick(EventThread.java:76)
       at io.socket.thread.EventThread.exec(EventThread.java:57)
       at io.socket.engineio.client.transports.WebSocket$2.onFailure(WebSocket.java:132)
       at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:543)
       at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:203)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

**Comment by emrealparslan93** [comment]
I got similar error:

`Fatal Exception: java.lang.InternalError: Thread starting during runtime shutdown
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:920)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1327)
       at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:583)
       at io.socket.thread.EventThread.nextTick(EventThread.java:76)
       at io.socket.thread.EventThread.exec(EventThread.java:57)
       at io.socket.engineio.client.transports.WebSocket$2.onFailure(WebSocket.java:132)
       at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:521)
       at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:202)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)`

**Comment by anu91balyan** [comment]
Hi 

we are also facing this issue very frequently. 

java.lang.InternalError: 
  at java.lang.Thread.nativeCreate (Native Method)
  at java.lang.Thread.start (Thread.java:733)
  at java.util.concurrent.ThreadPoolExecutor.addWorker (ThreadPoolExecutor.java:970)
  at java.util.concurrent.ThreadPoolExecutor.execute (ThreadPoolExecutor.java:1377)
  at java.util.concurrent.Executors$DelegatedExecutorService.execute (Executors.java:620)
  at com.github.nkzawa.thread.EventThread.nextTick (EventThread.java:71)
  at com.github.nkzawa.thread.EventThread.exec (EventThread.java:52)
  at com.github.nkzawa.engineio.client.transports.PollingXHR$1.call (PollingXHR.java:53)
  at com.github.nkzawa.emitter.Emitter.emit (Emitter.java:117)
  at com.github.nkzawa.engineio.client.transports.PollingXHR$Request.onResponseHeaders (PollingXHR.java:254)
  at com.github.nkzawa.engineio.client.transports.PollingXHR$Request.access$500 (PollingXHR.java:135)
  at com.github.nkzawa.engineio.client.transports.PollingXHR$Request$1.run (PollingXHR.java:210)
  at java.lang.Thread.run (Thread.java:764)

Kindly provide the solution for this issue  because App is live and we are getting same crashes regularly.

**Comment by amalnafia** [comment]
having the issue any updates on solutions?
