### ISSUE TITLE
版本不协调导致的问题

### ISSUE THREAD

**Issue by wangqiSoft** [socketio/socket.io-client-java#445]
服务器端的版本是0.9.0 ，我们android端使用的是1.0.0版本，在使用 mSocket.connect(); 的时候回报空指针错误，在PollingXHR.java 的第271行 ，body.contentType() 空指针。 以下是错误日志：

 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String okhttp3.MediaType.toString()' on a null object reference
                                                                          at io.socket.engineio.client.transports.PollingXHR$Request.onLoad(PollingXHR.java:271)
                                                                          at io.socket.engineio.client.transports.PollingXHR$Request.access$700(PollingXHR.java:148)
                                                                          at io.socket.engineio.client.transports.PollingXHR$Request$1.onResponse(PollingXHR.java:232)
                                                                          at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
                                                                          at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                          at java.lang.Thread.run(Thread.java:818)

**Comment by s9443112** [comment]
如果你client 沒用到ios 系統
你可以把server版本配置1.3.5,java端配置0.8.3 是穩定可行的

**Comment by VeerHan** [comment]
我刚刚解决了body.contentType()为空的问题，原因是客户的手机wifi连了代理。

**Comment by darrachequesne** [comment]
For future readers:

This should be fixed by https://github.com/socketio/engine.io-client-java/commit/6f065b7a62603730979d43cec71af0046ca4ab7c, included in all recent versions.

Please reopen if needed.
