### ISSUE TITLE
strange exception 

### ISSUE THREAD

**Issue by ordele** [socketio/socket.io-client-java#453]
Hi ,
do you familiar with this exception ? 
i'm not sure if it's comes from your library or others.
i'm using version 'io.socket:socket.io-client:0.7.0'
it's happening mainly in Asia area (Japan and china),and this exception come and go start from this week.

java.lang.IllegalStateException: stream != null
at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:155)
at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127)
at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:289)
at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
at okhttp3.RealCall.getResponse(RealCall.java:240)
at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
at okhttp3.RealCall.access$100(RealCall.java:30)
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:33)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
