### ISSUE TITLE
XHR Poll error 

### ISSUE THREAD

**Issue by Nixellion** [socketio/socket.io-client-java#463]
I'm writing an Android client for my Flask-SocketIO server. I managed to connect to it using chat app example, but whenever I try to emit anything (in my case - login information to authenticate), I get XHR Poll error:

```
09-19 15:45:58.715 27655-27655/ccc D/MainActivity: Get socket.
09-19 15:45:58.731 27655-27655/ccc D/MainActivity: Connecting with Socket...
09-19 15:45:58.732 27655-27655/ccc D/MainActivity: Authenticating
09-19 15:45:58.732 27655-27655/ccc D/MainActivity: Logged in?
09-19 15:45:58.749 27655-27655/ccc E/HAL: PATH3 /odm/lib64/hw/gralloc.qcom.so
09-19 15:45:58.749 27655-27655/ccc E/HAL: PATH2 /vendor/lib64/hw/gralloc.qcom.so
09-19 15:45:58.749 27655-27655/ccc E/HAL: PATH1 /system/lib64/hw/gralloc.qcom.so
09-19 15:45:58.749 27655-27655/ccc E/HAL: PATH3 /odm/lib64/hw/gralloc.msm8953.so
09-19 15:45:58.749 27655-27655/ccc E/HAL: PATH2 /vendor/lib64/hw/gralloc.msm8953.so
09-19 15:45:58.749 27655-27655/ccc E/HAL: PATH1 /system/lib64/hw/gralloc.msm8953.so
09-19 15:45:58.756 27655-27655/ccc D/ActivityThreadInjector: clearCachedDrawables.
09-19 15:45:58.762 27655-27689/ccc D/MainActivity: error: io.socket.engineio.client.EngineIOException: xhr poll error
```

What are the usual mistakes here?

```
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Log.d(LOG_TAG, "Get socket.");

        getSocket();

        Log.d(LOG_TAG, "Authenticating");

        JSONObject obj = new JSONObject();
        try {
            obj.put("name","name");
            obj.put("pass","pass");
        } catch (JSONException e) {e.printStackTrace();}

        socket.emit("authenticate", obj);

        Log.d(LOG_TAG, "Logged in?");


 public synchronized Socket getSocket() {
        if (socket == null) {
            try {
                SSLContext sc = SSLContext.getInstance("TLS");
                sc.init(null, trustAllCerts, new SecureRandom());

                HostnameVerifier myHostnameVerifier = new HostnameVerifier() {
                    @Override
                    public boolean verify(String hostname, SSLSession session) {
                        return true;
                    }
                };

                //IO.setDefaultSSLContext(sc);
                HttpsURLConnection.setDefaultHostnameVerifier(new RelaxedHostNameVerifier());

                OkHttpClient okHttpClient = new OkHttpClient.Builder()
                        .hostnameVerifier(myHostnameVerifier)
                        .sslSocketFactory(sc.getSocketFactory(), trustAllCerts2)
                        .build();

                // default settings for all sockets
                IO.setDefaultOkHttpWebSocketFactory(okHttpClient);
                IO.setDefaultOkHttpCallFactory(okHttpClient);

                // socket options
                IO.Options opts = new IO.Options();
                 // set as an option
                opts = new IO.Options();
                opts.callFactory = okHttpClient;
                opts.webSocketFactory = okHttpClient;


                opts.forceNew = true;
                opts.reconnection = false;
                opts.secure = false;
                //opts.sslContext = sc;
                //opts.hostnameVerifier = myHostnameVerifier;



                //opts.query = "password=nix04mania&username=nix";

                socket = IO.socket("https://foo.bar", opts);
                socket.on(Socket.EVENT_CONNECT, new Emitter.Listener() {

                    @Override
                    public void call(Object... args) {
                        Log.d(LOG_TAG, "Socket Connected");
                    }

                }).on("message", new Emitter.Listener() {

                    @Override
                    public void call(Object... args) {
                        Log.d(LOG_TAG, "'message' event: " + args[0].toString());
                    }

                }).on(Socket.EVENT_DISCONNECT, new Emitter.Listener() {

                    @Override
                    public void call(Object... args) {
                        Log.d(LOG_TAG, "Socket Disconnected");
                    }

                }).on(Socket.EVENT_CONNECT_ERROR, new Emitter.Listener() {

                    @Override
                    public void call(Object... args) {
                        Log.d(LOG_TAG, "error: " + args[0].toString());
                    }

                });
            } catch (URISyntaxException e) {
                e.printStackTrace();
            } catch (NoSuchAlgorithmException e) {
                e.printStackTrace();
            } catch (KeyManagementException e) {
                e.printStackTrace();
            }
        }
```

**Comment by HuaiAnGG** [comment]
i get this too.

**Comment by HuaiAnGG** [comment]
did you selved it???

**Comment by Nixellion** [comment]
@HuaiAnGG No, I did not. I was trying to make a personal voice assistant, and since I decided to just go with a web (browser) client for android devices and a raspberry pi for a dedicated unit.

**Comment by zl19940519** [comment]
did you selved it???

**Comment by brunorcabral** [comment]
Hi, for me the full stack error showed a SSLPeerUnverifiedException, saying my hostname was not verified.

```
com.github.nkzawa.engineio.client.EngineIOException: xhr poll error
        at com.github.nkzawa.engineio.client.Transport.onError(Transport.java:65)
        at com.github.nkzawa.engineio.client.transports.PollingXHR.access$100(PollingXHR.java:17)
        at com.github.nkzawa.engineio.client.transports.PollingXHR$6$1.run(PollingXHR.java:125)
        at com.github.nkzawa.thread.EventThread$2.run(EventThread.java:75)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: javax.net.ssl.SSLPeerUnverifiedException: Hostname myurl.com not verified:
```

I searched online and found that this is due to certificate error, but I trust the hostname, so, I need to pass in my own hostnameVerifier .

You commented the part where you enable the hostname verifier

```
//opts.hostnameVerifier = myHostnameVerifier;
```


For me I did this

Created a funtion to return my own hostnameVerifier 

```
private static HostnameVerifier getLiverfHostnameVerifier() {
        return new HostnameVerifier() {
            @Override
            public boolean verify(String hostname, SSLSession session) {
                return hostname.equals("trusturl1.com") || hostname.equals("trusturl2.net");
            }
        };
    }
```

then I use it as option to create the socket

```
IO.Options options = new IO.Options();
options.hostnameVerifier = getLiverfHostnameVerifier();
mSocket = IO.socket(HOSTNAME, options);
```

**Comment by darrachequesne** [comment]
Added in the documentation here: https://socketio.github.io/socket.io-client-java/initialization.html#SSL_connections

Please reopen if needed.
