### ISSUE TITLE
Error While debugging:

### ISSUE THREAD

**Issue by CoericK** [socketio/socket.io-client-java#47]
Hello Im getting this error in console while debugging:

I added this compile 'com.github.nkzawa:socket.io-client:0.2.0' on build.gradle because im using android studio.

```
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
    C:\Users\Erick\AppData\Local\Android\android-studio\sdk\build-tools\android-4.4W\dx.bat --dex --num-threads=4 --output D:\ProjectsImportedFromEclipse\WebSocketChat\app\build\intermediates\dex\debug D:\ProjectsImportedFromEclipse\WebSocketChat\app\build\intermediates\classes\debug D:\ProjectsImportedFromEclipse\WebSocketChat\app\build\intermediates\dependency-cache\debug D:\ProjectsImportedFromEclipse\WebSocketChat\app\build\intermediates\pre-dexed\debug\engine.io-client-0.3.0-443924d78a72e7b325e51936fe74a87663e8ed9e.jar D:\ProjectsImportedFromEclipse\WebSocketChat\app\build\intermediates\pre-dexed\debug\Java-WebSocket-1.3.0-f5c76730c2d6cdc8a3bf4d71ea67b620d48f79eb.jar D:\ProjectsImportedFromEclipse\WebSocketChat\app\build\intermediates\pre-dexed\debug\socket.io-client-0.2.0-2af807c83fbcf6a233217dffd53396f16924dc3f.jar D:\ProjectsImportedFromEclipse\WebSocketChat\app\build\intermediates\pre-dexed\debug\socketio-4e8d5dc694f956d686faa67307203cdfde9fb0af.jar
Error Code:
    2
Output:
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Lorg/java_websocket/WebSocketListener;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:594)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:552)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:533)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:170)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:439)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:287)
        at com.android.dx.command.dexer.Main.run(Main.java:230)
        at com.android.dx.command.dexer.Main.main(Main.java:199)
        at com.android.dx.command.Main.main(Main.java:103)
```

This is what im executing on my activity.

```
        Socket socket = null;
        try {
            socket = IO.socket("http://192.168.1.30:3000");
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }
        socket.on(Socket.EVENT_CONNECT, new Emitter.Listener() {

            @Override
            public void call(Object... args) {
                //socket.emit("foo", "hi");
                //socket.disconnect();
            }

        }).on("event", new Emitter.Listener() {

            @Override
            public void call(Object... args) {}

        }).on(Socket.EVENT_DISCONNECT, new Emitter.Listener() {

            @Override
            public void call(Object... args) {}

        });
        socket.connect();

```

**Comment by subbuboyapati** [comment]
@CoericK hey can you please tell me how to debug socket client java with all level of log levels in android?
