### ISSUE TITLE
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by pluzmedia** [socketio/socket.io-client-java#473]
I am getting the following errors in Android 5. Any help to resolve this would be appreciated.

Fatal Exception: java.lang.ArrayIndexOutOfBoundsException
length=24; index=314581152
 Raw Text
okio.Base64.encode (SourceFile:137)
okio.Base64.encode (SourceFile:125)
okio.ByteString.base64 (SourceFile:131)
okhttp3.internal.ws.RealWebSocket. (SourceFile)
okhttp3.OkHttpClient.newWebSocket (SourceFile:426)
io.socket.engineio.client.transports.WebSocket.doOpen (SourceFile:50)
io.socket.engineio.client.Transport$1.run (SourceFile:74)
io.socket.thread.EventThread.exec (SourceFile:55)
io.socket.engineio.client.Transport.open (SourceFile:69)
io.socket.engineio.client.Socket$2.run (SourceFile:263)
io.socket.thread.EventThread.exec (SourceFile:55)
io.socket.client.Manager$1.io.socket.engineio.client.Socket.open (SourceFile:1241)
io.socket.thread.EventThread.exec (SourceFile:55)
io.socket.client.Manager.open (SourceFile:266)
io.socket.client.Socket$3.io.socket.client.Manager.open (SourceFile:1256)
io.socket.thread.EventThread$2.run (SourceFile:80)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1112)
java.lang.Thread.run (Thread.java:818)

**Comment by Kazemir** [comment]
Yep, I've got this problem too. On Vobis Bay, Vobis Power Rage, Lenovo P1ma40 (all devices on Android 5).

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=24; index=588412032
       at okio.Base64.encode(Base64.java:137)
       at okio.Base64.encode(Base64.java:125)
       at okio.ByteString.base64(ByteString.java:131)
       at okhttp3.internal.ws.RealWebSocket.(RealWebSocket.java)
       at okhttp3.OkHttpClient.newWebSocket(OkHttpClient.java:435)
       at io.socket.engineio.client.transports.WebSocket.doOpen(WebSocket.java:78)
       at io.socket.engineio.client.Transport$1.run(Transport.java:82)
       at io.socket.thread.EventThread.exec(EventThread.java:55)
       at io.socket.engineio.client.Transport.open(Transport.java:77)
       at io.socket.engineio.client.Socket$2.run(Socket.java:248)
       at io.socket.thread.EventThread.exec(EventThread.java:55)
       at io.socket.engineio.client.Socket.open(Socket.java:226)
       at io.socket.client.Manager$1.run(Manager.java:330)
       at io.socket.thread.EventThread.exec(EventThread.java:55)
       at io.socket.client.Manager.open(Manager.java:250)
       at io.socket.client.Manager.open(Manager.java:240)
       at io.socket.client.Socket$3.run(Socket.java:133)
       at io.socket.thread.EventThread$2.run(EventThread.java:80)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by Kazemir** [comment]
This problem occurs when using D8 compiler. Details is here: https://github.com/square/okio/issues/325

**Comment by pluzmedia** [comment]
Thanks for letting me know. Do you have any workaround?

**Comment by Kazemir** [comment]
Set the following in your project's gradle.properties file:
> android.enableD8=false

**Comment by pluzmedia** [comment]
Thank man for the help. It solved my problem.

**Comment by anupdey99** [comment]
3.1.3 (June 2018)
This update to Android Studio 3.1 includes fixes for the following bugs:

Memory leaks caused Android Studio to become slow and unresponsive after you had been using the Layout Editor. This update includes fixes for most of these issues. We intend to release another update soon to address additional memory leaks.

**Some applications built with D8 crashed on some Verizon Ellipsis tablets.**

**Installation of applications built with D8 failed with an INSTALL_FAILED_DEXOPT error on devices running Android 5.0 or 5.1 (API level 21 or 22).**

**Some applications that used the OkHttp library and were built with D8 crashed on devices running Android 4.4 (API level 19).**

Android Studio sometimes failed to start, with a ProcessCanceledException during class initialization for com.intellij.psi.jsp.JspElementType.

**Comment by gsetia402** [comment]
android.enableD8=false 
This solution might be resolved your issue to some extent but it could be a nightmare because D8 allows us to use Java 8 language features in our app's code. 
I would not recommend this solution.

Try updating Android Studio and Build tool version to the latest.
