### ISSUE TITLE
StopIteration error on connection

### ISSUE THREAD

**Issue by berkayaslan** [socketio/socket.io-client-java#477]
> Traceback (most recent call last):
>   File "client.py", line 6, in <module>
>    with SocketIO('http:/.....herokuapp.com', 80, LoggingNamespace) as socketIO:
>  File "/usr/local/lib/python3.5/dist-packages/socketIO_client/__init__.py", line 353, in __init__
>    resource, hurry_interval_in_seconds, **kw)
>  File "/usr/local/lib/python3.5/dist-packages/socketIO_client/__init__.py", line 54, in __init__
>    self._transport
>  File "/usr/local/lib/python3.5/dist-packages/socketIO_client/__init__.py", line 62, in _transport
>    self._engineIO_session = self._get_engineIO_session()
>  File "/usr/local/lib/python3.5/dist-packages/socketIO_client/__init__.py", line 76, in _get_engineIO_session
>    transport.recv_packet())
> StopIteration

It throws this error. Here is my connection code:

`from socketIO_client import SocketIO, LoggingNamespace

with SocketIO('http://........herokuapp.com', 80, LoggingNamespace) as socketIO:
    socketIO.emit('Title', 'something')
`

any solutıon ?

**Comment by berkayaslan** [comment]
Wrong place i'm sorry
