### ISSUE TITLE
Bug in SDK10!

### ISSUE THREAD

**Issue by QuestionPython** [socketio/socket.io-client-java#487]
AndroidManifest
-------
```
android {
    compileSdkVersion 26
    buildToolsVersion "26.0.0"
    defaultConfig {
        applicationId "com.test.me"
        minSdkVersion 10
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile ('io.socket:socket.io-client:1.0.0') {
        exclude group: 'org.json', module: 'json'
    }
    testCompile 'junit:junit:4.12'
}
```

```
01-06 13:10:24.092 2714-2714/com.test.me E/AndroidRuntime: FATAL EXCEPTION: main
                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{com.test.me/com.test.me.Main}: android.content.res.Resources$NotFoundException: Resource ID #0x7f040020
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2211)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
                                                                 at android.app.ActivityThread.access$600(ActivityThread.java:141)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                 at android.os.Looper.loop(Looper.java:137)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5103)
                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:525)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                 at dalvik.system.NativeStart.main(Native Method)
                                                              Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f040020
                                                                 at android.content.res.Resources.getValue(Resources.java:1118)
                                                                 at android.content.res.Resources.loadXmlResourceParser(Resources.java:2304)
                                                                 at android.content.res.Resources.getLayout(Resources.java:934)
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:395)
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                 at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:267)
                                                                 at android.app.Activity.setContentView(Activity.java:1895)
                                                                 at com.test.me.Main.onCreate(Main.java:11)
                                                                 at android.app.Activity.performCreate(Activity.java:5133)
                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261) 
                                                                 at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                 at android.os.Looper.loop(Looper.java:137) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5103) 
                                                                 at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                 at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737) 
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                                 at dalvik.system.NativeStart.main(Native Method) 
```

But after delete ```compile ('io.socket:socket.io-client:1.0.0') {...}``` , app build and work!

min sdk for socket.io is not 10!? (https://github.com/socketio/socket.io-client-java/issues/278)

how fix problem?

**Comment by questionpython** [comment]
Fixed With : 
```
    compile ('io.socket:socket.io-client:0.6.3') {
        exclude group: 'org.json', module: 'json'
    }
```
or
```
    compile ('io.socket:socket.io-client:0.9.0') {
        exclude group: 'org.json', module: 'json'
    }
```

**Comment by darrachequesne** [comment]
That should be fixed in latest version, please reopen if needed.
