### ISSUE TITLE
Crash socket-io-client

### ISSUE THREAD

**Issue by Nikonov** [socketio/socket.io-client-java#508]
Crash when server emit event. Socket.io-client:0.9.0.

`03-12 13:21:42.944 6958-7039/org.smartplayer.client.develop E/EventThread: Task threw exception
                                                                           java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
                                                                               at io.socket.client.Socket.onevent(Socket.java:349)
                                                                               at io.socket.client.Socket.onpacket(Socket.java:303)
                                                                               at io.socket.client.Socket.access$100(Socket.java:19)
                                                                               at io.socket.client.Socket$2$2.call(Socket.java:115)
                                                                               at io.socket.emitter.Emitter.emit(Emitter.java:117)
                                                                               at io.socket.client.Manager.ondecoded(Manager.java:409)
                                                                               at io.socket.client.Manager.access$1600(Manager.java:22)
                                                                               at io.socket.client.Manager$7.call(Manager.java:385)
                                                                               at io.socket.emitter.Emitter.emit(Emitter.java:117)
                                                                               at io.socket.parser.Parser$Decoder.add(Parser.java:157)
                                                                               at io.socket.client.Manager.ondata(Manager.java:401)
                                                                               at io.socket.client.Manager.access$1000(Manager.java:22)
                                                                               at io.socket.client.Manager$2.call(Manager.java:352)
                                                                               at io.socket.emitter.Emitter.emit(Emitter.java:117)
                                                                               at io.socket.engineio.client.Socket.onPacket(Socket.java:521)
                                                                               at io.socket.engineio.client.Socket.access$1000(Socket.java:35)
                                                                               at io.socket.engineio.client.Socket$5.call(Socket.java:321)
                                                                               at io.socket.emitter.Emitter.emit(Emitter.java:117)
                                                                               at io.socket.engineio.client.Transport.onPacket(Transport.java:126)
                                                                               at io.socket.engineio.client.Transport.onData(Transport.java:118)
                                                                               at io.socket.engineio.client.transports.WebSocket.access$100(WebSocket.java:24)
                                                                               at io.socket.engineio.client.transports.WebSocket$1$2.run(WebSocket.java:71)
                                                                               at io.socket.thread.EventThread$2.run(EventThread.java:80)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                               at java.lang.Thread.run(Thread.java:818)
03-12 13:21:42.944 6958-7039/org.smartplayer.client.develop E/AndroidRuntime: FATAL EXCEPTION: EventThread
                                                                              Process: org.smartplayer.client.develop, PID: 6958
                                                                              java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
                                                                                  at io.socket.client.Socket.onevent(Socket.java:349)
                                                                                  at io.socket.client.Socket.onpacket(Socket.java:303)
                                                                                  at io.socket.client.Socket.access$100(Socket.java:19)
                                                                                  at io.socket.client.Socket$2$2.call(Socket.java:115)
                                                                                  at io.socket.emitter.Emitter.emit(Emitter.java:117)
                                                                                  at io.socket.client.Manager.ondecoded(Manager.java:409)
                                                                                  at io.socket.client.Manager.access$1600(Manager.java:22)
                                                                                  at io.socket.client.Manager$7.call(Manager.java:385)
                                                                                  at io.socket.emitter.Emitter.emit(Emitter.java:117)
                                                                                  at io.socket.parser.Parser$Decoder.add(Parser.java:157)
                                                                                  at io.socket.client.Manager.ondata(Manager.java:401)
                                                                                  at io.socket.client.Manager.access$1000(Manager.java:22)
                                                                                  at io.socket.client.Manager$2.call(Manager.java:352)
                                                                                  at io.socket.emitter.Emitter.emit(Emitter.java:117)
                                                                                  at io.socket.engineio.client.Socket.onPacket(Socket.java:521)
                                                                                  at io.socket.engineio.client.Socket.access$1000(Socket.java:35)
                                                                                  at io.socket.engineio.client.Socket$5.call(Socket.java:321)
                                                                                  at io.socket.emitter.Emitter.emit(Emitter.java:117)
                                                                                  at io.socket.engineio.client.Transport.onPacket(Transport.java:126)
                                                                                  at io.socket.engineio.client.Transport.onData(Transport.java:118)
                                                                                  at io.socket.engineio.client.transports.WebSocket.access$100(WebSocket.java:24)
                                                                                  at io.socket.engineio.client.transports.WebSocket$1$2.run(WebSocket.java:71)
                                                                                  at io.socket.thread.EventThread$2.run(EventThread.java:80)
                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                  at java.lang.Thread.run(Thread.java:818)`

**Comment by gizmeondev** [comment]
any suggestion regarding this issue

**Comment by rameshkec85** [comment]
@gizmeondev Do u have any solution ?

**Comment by RomanHiden** [comment]
I am affected as well.

**Comment by faizalmp** [comment]
I have the same issue. Any solution?

**Comment by RomanHiden** [comment]
@faizalmp  for me it was due to passing null as socketId .something like that. but still its not handled properly by the library

**Comment by iagormoraes** [comment]
the lib crashes in the emit event by sending or receiving(not sure), if you add a null in JSONArray it will crash, but if you wrap the array inside JSONObject it works.

**Comment by darrachequesne** [comment]
For future readers:

This should be fixed by https://github.com/socketio/socket.io-client-java/commit/e8ffe9d1383736f6a21090ab959a2f4fa5a41284, which was included in version `2.0.1`.

This commit was also [backported](https://github.com/socketio/socket.io-client-java/commit/8664499b6f31154f49783531f778dac5387b766b) to the 1.x branch, and included in version `1.0.2`.

Please reopen if needed.
