### ISSUE TITLE
Cannot connect socketio and always get errors

### ISSUE THREAD

**Issue by namson0482** [socketio/socket.io-client-java#532]
Hi

I use socket.io-client library to connect my server but i always get errors like below:
thg 6 14, 2018 11:38:14 SA io.socket.thread.EventThread$2 run
SEVERE: Task threw exception
java.lang.NoClassDefFoundError: okhttp3/Call$Factory
	at io.socket.client.Manager$1.run(Manager.java:277)
	at io.socket.thread.EventThread.exec(EventThread.java:55)
	at io.socket.client.Manager.open(Manager.java:266)
	at io.socket.client.Manager.open(Manager.java:256)
	at io.socket.client.Socket$3.run(Socket.java:142)
	at io.socket.thread.EventThread$2.run(EventThread.java:80)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: okhttp3.Call$Factory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more

Exception in thread "EventThread" java.lang.NoClassDefFoundError: okhttp3/Call$Factory
	at io.socket.client.Manager$1.run(Manager.java:277)
	at io.socket.thread.EventThread.exec(EventThread.java:55)
	at io.socket.client.Manager.open(Manager.java:266)
	at io.socket.client.Manager.open(Manager.java:256)
	at io.socket.client.Socket$3.run(Socket.java:142)
	at io.socket.thread.EventThread$2.run(EventThread.java:80)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: okhttp3.Call$Factory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more

My java code is like below:
import io.socket.client.IO;
import io.socket.client.Socket;
import io.socket.emitter.Emitter;

public class SocketExample {

	public static void main(String[] args) {
		
		try {
			IO.Options opts = new IO.Options();
			/** opts.forceNew = true; */
			opts.query = "token=" + "INTERNAL_SYSTEM";
			Socket socket = IO.socket("http://localhost:3000", opts);
			socket.on(Socket.EVENT_CONNECT, new Emitter.Listener() {
				@Override
				public void call(Object... args) {
					socket.emit("add user", "newsonvu");
				}

			}).on("event", new Emitter.Listener() {

				@Override
				public void call(Object... args) {
					System.out.println("event " + args.length);
				}

			}).on(Socket.EVENT_DISCONNECT, new Emitter.Listener() {
				@Override
				public void call(Object... args) {

				}

			});
			socket.connect();
			
			System.out.println("Vu Nam Son");
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}

And My server code is javascript like below:

// Setup basic express server
var express = require('express');
var app = express();
var path = require('path');
var server = require('http').createServer(app);
var io = require('../..')(server);
var port = process.env.PORT || 3000;

server.listen(port, () => {
  console.log('Server listening at port %d', port);
});

// Routing
app.use(express.static(path.join(__dirname, 'public')));

// Chatroom

var numUsers = 0;

io.on('connection', (socket) => {
  var addedUser = false;

  // when the client emits 'new message', this listens and executes
  socket.on('new message', (data) => {
    // we tell the client to execute 'new message'
    socket.broadcast.emit('new message', {
      username: socket.username,
      message: data
    });
  });

  // when the client emits 'add user', this listens and executes
  socket.on('add user', (username) => {
    if (addedUser) return;

    // we store the username in the socket session for this client
    socket.username = username;
    ++numUsers;
    addedUser = true;
    socket.emit('login', {
      numUsers: numUsers
    });
	
	console.log('Total user joined %d', numUsers);
	
    // echo globally (all clients) that a person has connected
    socket.broadcast.emit('user joined', {
      username: socket.username,
      numUsers: numUsers
    });
  });

  // when the client emits 'typing', we broadcast it to others
  socket.on('typing', () => {
    socket.broadcast.emit('typing', {
      username: socket.username
    });
  });

  // when the client emits 'stop typing', we broadcast it to others
  socket.on('stop typing', () => {
    socket.broadcast.emit('stop typing', {
      username: socket.username
    });
  });

  // when the user disconnects.. perform this
  socket.on('disconnect', () => {
    if (addedUser) {
      --numUsers;
	console.log('User disconnect');
      // echo globally that this client has left
      socket.broadcast.emit('user left', {
        username: socket.username,
        numUsers: numUsers
      });
    }
  });
});

I try to do this for 3 days. But i do not know root cause. Please help me if you know reason

**Comment by dylankolson** [comment]
I am getting the same issue any luck?

**Comment by namson0482** [comment]
For me, I just open m2 folder of repository and delete all library of socket io and let maven download library again then it will be ok

**Comment by neilyoung** [comment]
Same problem here. All depending libraries in path. 

java.lang.NoClassDefFoundError: okhttp3/Call$Factory

**Comment by darrachequesne** [comment]
For future readers:

This looks like a dependency issue, we now use `okhttp@3.12.12`: https://github.com/socketio/engine.io-client-java/commit/8016a5d7462f9379b4ad0f5660188c8626319ca6

Please reopen if needed.
