### ISSUE TITLE
ClassException: java.lang.ClassCastException: com.github.nkzawa.socketio.client.Socket$7 

### ISSUE THREAD

**Issue by GargNishant** [socketio/socket.io-client-java#551]
So I am new to this. What we are doing is using the rabbitMq to send the message to my local server which is made on Node.js. The events are getting triggered properly but when it comes to parsing the incoming message it is showing error. I am including the server side Code, my app code and the error itself. The server side code is not by me but my colleague. Android stuff is done by me.

Node.Js server File
[app.txt](https://github.com/socketio/socket.io-client-java/files/2310375/app.txt)

This is a sample app. My main activity
[MainActivity.txt](https://github.com/socketio/socket.io-client-java/files/2310383/MainActivity.txt)

Server Side code in File 
```
// import { close } from 'fs';

var express = require('express');
var path = require('path');
var app = express();
var server = require('http').Server(app);
var io = require('socket.io')(server);
var amqp = require('amqplib/callback_api');


var port = 8000;

var que = "Test"
var ex = "livestream"
var messages = [];

app.use(express.static(path.join(__dirname, "public")));


// app.get("/",(req,res)=>es.send("Hello world"));

io.on('connection', (socket) => {
  console.log('new connection made');

  // socket.on('event1', (data) => {
  //   console.log(data.msg);
  // });


  // socket.emit('event2', {
  //   msg: 'Server to client, do you read me? Over.'
  // });


  socket.emit('Test', (data)=>{
    console.log("sending message :%s", messages);
    socket.emit('Test',{msg:messages[0]
    });
    
  });

  // socket.on('event3', (data) => {
  //   console.log(data.msg);
  //   socket.emit('event4', {
  //     msg: 'Loud and clear :)'
  //   });
  // });
});

// console.log("yay")
amqp.connect('amqp://52.37.151.97', function (err, conn) {

  console.log("connection made");
  conn.createChannel(function (err, ch) {
    // if(closeOnErr(err))return;
    ch.on("close",function(err){
      console.error("[  aqmp]c channel error",err.messages);
    });
    ch.on("close",function(){
      console.log("Channel closed");
    });

    // var q = 'hello';

    // ch.assertQueue(q, { durable: false });
    // console.log(q);

    ch.assertExchange(ex, 'topic', { durable: false });
    console.log()

    ch.assertQueue('Test', { durable: false }, function (err, q) {
      ch.prefetch(1);
      console.log(' [*] Waiting for logs. To exit press CTRL+C');
      ch.bindQueue(q.queue, ex, "alert");
      console.log(q.queue);

      ch.consume(q.queue, function(msg) {
        ch.ack(msg);
        console.log(" [x] %s: '%s'", msg.fields.routingKey, msg.content.toString());


        messages.push(msg.content.toString());
        console.log("messages[0] :",messages[0]);
        // JSON.parse(msg)
    }, 
    { 
      noAck: false 
    });


      // console.log(" [*] Waiting for messages in %s. To exit press CTRL+C", q);

      // ch.consume(q, function (msg) {
      //   console.log(" [x] Received %s", msg.content.toString());
      //   messages.push(msg.content.toString());
      //   console.log("message[0] :", messages[0]);
      // },
      //   {
      //     noAck: true

      //   });

    });
  });
});

// console.log(" [*] Waiting for messages in %s. To exit press CTRL+C", q);z
server.listen(port, () => {
  console.log("Listening on port " + port);
});
```

Main Activity Code: 

```java
package com.example.zest.sampleproject;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.text.TextUtils;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

import com.github.nkzawa.socketio.client.IO;
import com.github.nkzawa.socketio.client.Socket;
import com.github.nkzawa.emitter.Emitter;

import org.json.JSONException;
import org.json.JSONObject;

import java.net.URISyntaxException;
import java.util.Arrays;

public class MainActivity extends AppCompatActivity {

    private Socket mSocket;
    {
        try {
            mSocket = IO.socket("http://192.168.122.1:8000");
        } catch (URISyntaxException e) {
            throw new RuntimeException(e);
        }
    }

    private EditText editText;
    private Button button;
    private TextView textView;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        editText = findViewById(R.id.editText);
        textView = findViewById(R.id.textView);
        button = findViewById(R.id.button);

        mSocket.on(Socket.EVENT_CONNECT,onConnect);
        mSocket.on("Test", onNewMessage);
        mSocket.connect();
        mSocket.open();

//        mSocket.on(Socket.EVENT_CONNECT, new Emitter.Listener() {
//
//            @Override
//            public void call(Object... args) {
//                mSocket.emit("foo", "hi");
//                mSocket.disconnect();
//            }
//
//        }).on("event", new Emitter.Listener() {
//
//            @Override
//            public void call(Object... args) {}
//
//        }).on(Socket.EVENT_DISCONNECT, new Emitter.Listener() {
//
//            @Override
//            public void call(Object... args) {}
//
//        });
//        mSocket.connect();

        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                attemptSend();
            }
        });
    }



    private void attemptSend() {
        String message = editText.getText().toString().trim();
        if (TextUtils.isEmpty(message)) {
            return;
        }
            textView.setText("");
            mSocket.emit("new message", message);
    }

    private Emitter.Listener onConnect = new Emitter.Listener() {
        @Override
        public void call(Object... args) {
            //Toast.makeText(MainActivity.this, "Connected", Toast.LENGTH_SHORT).show();
            Log.e("IsConnected:", String.valueOf(mSocket.connected()));
            mSocket.open();
        }
    };

    private Emitter.Listener onNewMessage = new Emitter.Listener() {
        @Override
        public void call(final Object... args) {
            MainActivity.this.runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    JSONObject object = (JSONObject) args[0];
                    Log.e("Length:", String.valueOf(args.length));
                    Log.e("Msg", object.toString());
                }
            });
        }
    };

}

```

Gradle: 
```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0-rc01'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

    implementation 'com.github.nkzawa:socket.io-client:0.5.0'

    implementation ('io.socket:socket.io-client:1.0.0') {
        // excluding org.json which is provided by Android
        exclude group: 'org.json', module: 'json'
    }
}
```

I followed the link from here https://socket.io/blog/native-socket-io-and-android/
And by the way That is all the activity my app contains. Its a sample app only open connection, parse the msg. No pom.xml  is there, and i don't know how to create one

My error:

```
08-22 18:40:05.600 3588-3651/com.example.zest.sampleproject E/IsConnected:: true
08-22 18:40:05.676 3588-3588/com.example.zest.sampleproject D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
08-22 18:40:05.676 3588-3588/com.example.zest.sampleproject E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.zest.sampleproject, PID: 3588
    java.lang.ClassCastException: com.github.nkzawa.socketio.client.Socket$7 cannot be cast to org.json.JSONObject
        at com.example.zest.sampleproject.MainActivity$3$1.run(MainActivity.java:106)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```

**Comment by GargNishant** [comment]
Upon parsing it with toString() method and printing it in Logs the response is {[com.github.nkzawa.socketio.client.Socket$7]}

**Comment by Jenjen1324** [comment]
I'm not familiar with rabbitMq but this line is a bit odd:

```js
  socket.emit('Test', (data)=>{
    console.log("sending message :%s", messages);
    socket.emit('Test',{msg:messages[0]
    });
```

You are emitting a function to your client, shouldn't it be `socket.on('Test', etc...` or just `socket.emit('Test', {data})`

**Comment by GargNishant** [comment]
I don't know about node js. But you can close the issue. It fixed on it's
own. I think it was from server side.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
