### ISSUE TITLE
Invalid namespace

### ISSUE THREAD

**Issue by MichaelJokAr** [socketio/socket.io-client-java#561]
String mynamespace = "/im/user";
IO.socket("http://localhost/mynamespace");
```
com.foxpower.flchatofandroid W/IOParser: An error occured while retrieving data from JSONTokener
    org.json.JSONException: Expected literal value at character 0 of ,"Invalid namespace"
        at org.json.JSONTokener.syntaxError(JSONTokener.java:449)
        at org.json.JSONTokener.readLiteral(JSONTokener.java:284)
        at org.json.JSONTokener.nextValue(JSONTokener.java:111)
        at io.socket.parser.IOParser$Decoder.decodeString(IOParser.java:181)
        at io.socket.parser.IOParser$Decoder.add(IOParser.java:94)
        at io.socket.client.Manager.ondata(Manager.java:419)
        at io.socket.client.Manager.access$1000(Manager.java:30)
        at io.socket.client.Manager$2.call(Manager.java:370)
        at io.socket.emitter.Emitter.emit(Emitter.java:117)
        at io.socket.engineio.client.Socket.onPacket(Socket.java:551)
        at io.socket.engineio.client.Socket.access$1000(Socket.java:36)
        at io.socket.engineio.client.Socket$5.call(Socket.java:335)
        at io.socket.emitter.Emitter.emit(Emitter.java:117)
        at io.socket.engineio.client.Transport.onPacket(Transport.java:126)
        at io.socket.engineio.client.transports.Polling.access$700(Polling.java:18)
        at io.socket.engineio.client.transports.Polling$2.call(Polling.java:127)
        at io.socket.engineio.parser.Parser.decodePayload(Parser.java:299)
        at io.socket.engineio.client.transports.Polling._onData(Polling.java:137)
        at io.socket.engineio.client.transports.Polling.onData(Polling.java:107)
        at io.socket.engineio.client.transports.PollingXHR$5$1.run(PollingXHR.java:127)
        at io.socket.thread.EventThread$2.run(EventThread.java:80)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)

```

**Comment by MichaelJokAr** [comment]
sorry ,It's my service error.

**Comment by PrachipriyaPrasad** [comment]
I'm also getting same error can u please tell me how you resolved this error.

**Comment by MichaelJokAr** [comment]
@PrachipriyaPrasad
because the version not right.
my server use v1.0+(nettrySocket.io), and I use the v2.0 to connect .
you can reduce your version to connect server

**Comment by PrachipriyaPrasad** [comment]
thanks for responding

**Comment by cash2910** [comment]
try 0.8.3
