### ISSUE TITLE
连接时怎么选择NameSpace

### ISSUE THREAD

**Issue by lwcloud** [socketio/socket.io-client-java#571]
连接时怎么选择NameSpace，和js一样我在url后面拼接
IO.socket("http://127.0.0.1:1001/im/user/?userid=test",options);

提示这个错误

二月 22, 2019 5:19:38 下午 io.socket.parser.IOParser$Decoder decodeString
警告: An error occured while retrieving data from JSONTokener
org.json.JSONException: Missing value at character 0
	at org.json.JSONTokener.syntaxError(JSONTokener.java:410)
	at org.json.JSONTokener.nextValue(JSONTokener.java:369)
	at io.socket.parser.IOParser$Decoder.decodeString(IOParser.java:181)
	at io.socket.parser.IOParser$Decoder.add(IOParser.java:94)
	at io.socket.client.Manager.ondata(Manager.java:419)
	at io.socket.client.Manager.access$1000(Manager.java:30)
	at io.socket.client.Manager$2.call(Manager.java:370)
	at io.socket.emitter.Emitter.emit(Emitter.java:117)
	at io.socket.engineio.client.Socket.onPacket(Socket.java:551)
	at io.socket.engineio.client.Socket.access$1000(Socket.java:36)
	at io.socket.engineio.client.Socket$5.call(Socket.java:335)
	at io.socket.emitter.Emitter.emit(Emitter.java:117)
	at io.socket.engineio.client.Transport.onPacket(Transport.java:126)
	at io.socket.engineio.client.Transport.onData(Transport.java:118)
	at io.socket.engineio.client.transports.WebSocket.access$100(WebSocket.java:24)
	at io.socket.engineio.client.transports.WebSocket$1$2.run(WebSocket.java:71)
	at io.socket.thread.EventThread$2.run(EventThread.java:80)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by bobo266163** [comment]
我遇到了和你一样的问题，如果你有解决方法的话，麻烦告诉我一下怎么解决的，QQ848454487

**Comment by windstear** [comment]
这个是因为他对packet做encoding的时候,强制追加了一个","进去
IOParser:55

**Comment by beiluo0** [comment]
我升级到1.7.17版本后没有报错了，之前用的1.7.12

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
