### ISSUE TITLE
java.net.URISyntaxException: Illegal character in scheme name at index 0: 10.0.0.42:65432

### ISSUE THREAD

**Issue by james04gr** [socketio/socket.io-client-java#621]
While i am trying to connect to a local server with specigic IP i get the following error.

`fun connectSocket() {
        
        val socket = IO.socket("10.0.0.42:65432")
        socket.on(Socket.EVENT_CONNECT) {
            println("Socket.EVENT_CONNECT")
            // socket.disconnect()
        }.on("event") {
            println("on Event")
        }.on(Socket.EVENT_DISCONNECT) {
            println("Socket.EVENT_DISCONNECT")
        }
        socket.connect()
    }`

`java.net.URISyntaxException: Illegal character in scheme name at index 0: 10.0.0.42:65432
        at java.net.URI$Parser.fail(URI.java:2892)
        at java.net.URI$Parser.checkChars(URI.java:3065)
        at java.net.URI$Parser.checkChar(URI.java:3075)
        at java.net.URI$Parser.parse(URI.java:3091)
        at java.net.URI.<init>(URI.java:583)
        at com.github.nkzawa.socketio.client.IO.socket(IO.java:37)
        at com.github.nkzawa.socketio.client.IO.socket(IO.java:33)`

**Comment by darrachequesne** [comment]
I think you are missing the scheme part, either `http://10.0.0.42:65432` or `https://10.0.0.42:65432`.

Documentation added here: https://socketio.github.io/socket.io-client-java/initialization.html#Creation_of_a_Socket_instance
