### ISSUE TITLE
[Android] .so file is not found when trying to use the socket.io-client library in Android app

### ISSUE THREAD

**Issue by rakeshostwal1** [socketio/socket.io-client-java#626]
I am creating an application where app will have OTG fingerprint authentication and video streaming using WebRTC, to use fingerprint sensor, I have used system custom system.so libraries given by the OTG Fingerprint vendor, and it is working fine, but when I try to add the `com.github.nkzawa:socket.io-client` along with `io.pristine:libjingle:9127@aar`, I am getting issue in .so file not found to the app while compiling.

I tried many solutions but nothing is working, any help will be much appreciated. 

Following error I am getting after adding this library in my Android project:

>
    Process: com.fingerprint.rcapp, PID: 7793
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.fingerprint.rcapp--XpzGpbTo00QmDUMlC48fQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.fingerprint.rcapp--XpzGpbTo00QmDUMlC48fQ==/lib/arm64, /data/app/com.fingerprint.rcapp--XpzGpbTo00QmDUMlC48fQ==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]] couldn't find "libast2600.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.fingerprint.rcapp.astdev.natives.PfsBioFpJNI.<clinit>(PfsBioFpJNI.java:95)
        at com.fingerprint.rcapp.astdev.natives.PfsBioFpJNI.createInstance(PfsBioFpJNI.java:110)
        at com.fingerprint.rcapp.astdev.natives.Ast2600.<init>(Ast2600.java:41)
        at com.fingerprint.rcapp.LoginActivity.onCreate(LoginActivity.java:98)
        at android.app.Activity.performCreate(Activity.java:7955)
        at android.app.Activity.performCreate(Activity.java:7944)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3423)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7814)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)

**Comment by rakeshostwal1** [comment]
Nvermind, this issue is not due to this library, closing this issue
