### ISSUE TITLE
IncompatibleClassChangeError when consuming response from server v4

### ISSUE THREAD

**Issue by wkrzywiec** [socketio/socket.io-client-java#690]
**Describe the bug**
I'm building the Socket.io server using Java library - [trinopoty/socket.io-server-java](https://github.com/trinopoty/socket.io-server-java) and now I would like to write some integration tests using this library. 

When the connection with server is established, i.e server is sending initial 200 response with body:

```
0{"pingInterval":25000,"pingTimeout":20000,"upgrades":["websocket"],"sid":"7PRUGwUPF45"}
```

for the request GET `http://localhost:8080/socket.io/?EIO=4&transport=polling`, and exception is thrown on a client side:

```java
java.lang.IncompatibleClassChangeError: Method io.socket.engineio.parser.Parser.decodePayload(Ljava/lang/String;Lio/socket/engineio/parser/Parser$DecodePayloadCallback;)V must be InterfaceMethodref constant
	at io.socket.engineio.client.transports.Polling._onData(Polling.java:131) ~[engine.io-client-2.0.0.jar:na]
	at io.socket.engineio.client.transports.Polling.onData(Polling.java:101) ~[engine.io-client-2.0.0.jar:na]
	at io.socket.engineio.client.transports.PollingXHR$5$1.run(PollingXHR.java:117) ~[engine.io-client-2.0.0.jar:na]
	at io.socket.thread.EventThread$2.run(EventThread.java:80) ~[engine.io-client-2.0.0.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

Exception in thread "EventThread" java.lang.IncompatibleClassChangeError: Method io.socket.engineio.parser.Parser.decodePayload(Ljava/lang/String;Lio/socket/engineio/parser/Parser$DecodePayloadCallback;)V must be InterfaceMethodref constant
	at io.socket.engineio.client.transports.Polling._onData(Polling.java:131)
	at io.socket.engineio.client.transports.Polling.onData(Polling.java:101)
	at io.socket.engineio.client.transports.PollingXHR$5$1.run(PollingXHR.java:117)
	at io.socket.thread.EventThread$2.run(EventThread.java:80)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**To Reproduce**

Socket.IO server version: `3.0.2` ([trinopoty/socket.io-server-java](https://github.com/trinopoty/socket.io-server-java)) 

*Server*

Implementation based on https://github.com/trinopoty/socket.io-server-java/issues/18#issuecomment-909389666 .

If needed I can provide full example code of it.

Socket.IO java client version: `2.0.1`

*Client*

My application is run with Spring Boot and here is my simple integration test example:

```java
@Test
    void shouldTest() throws URISyntaxException, InterruptedException {
        //given
       var map = new ConcurrentHashMap<String, String>();

        var url = "http://localhost:" + String.valueOf(port) + "/";
        Socket socket = IO.socket(url);

        socket.on(Socket.EVENT_CONNECT, (data) -> {
            System.out.println("Socket.EVENT_CONNECT");
        });

        socket.on("event", args -> {
            System.out.println("SocketEvent.PROJECT_CREATED.value()");
            map.put("event", (String) args[0]);
        });

        socket.connect();

        // when
        publisher.publishMessage("room", "event", "test message");

       //then
        assertEquals(1, map.size());
    }
```

**Expected behavior**
Client should not throw such error when performing standard connection.

**Platform:**
 - Spring Boot

**Additional context**
I've tested the server with a simple React application using the ` "socket.io-client": "^4.3.2"` library and everything works fine, therefore it seems as a client side problem.

Thanks in advance for all your support

**Comment by oddmario** [comment]
Could reproduce this, were you able to solve it?

**Comment by oddmario** [comment]
Figured it out. In my case I had both the server and the client running on the same project.

The conflict happens between https://github.com/socketio/engine.io-server-java/blob/master/engine.io-server/src/main/java/io/socket/engineio/parser/Parser.java (used by trinopoty's Socket.IO server) and https://github.com/socketio/socket.io-client-java/blob/master/src/main/java/io/socket/parser/Parser.java (used by this client), they both share the same package & class names which causes the issue.

As a temporary workaround, I decided to run each of the server and the client in seperate projects which fixed the conflict happening.
