### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference 

### ISSUE THREAD

**Issue by makadia7081** [socketio/socket.io-client-java#761]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference at io.socket.client.Socket.onevent(Socket.java:337) at io.socket.client.Socket.onpacket(Socket.java:289) at io.socket.client.Socket.access$100(Socket.java:24) at io.socket.client.Socket$2$2.call(Socket.java:120) at io.socket.emitter.Emitter.emit(Emitter.java:117) at io.socket.client.Manager.ondecoded(Manager.java:427) at io.socket.client.Manager.access$1600(Manager.java:30) at io.socket.client.Manager$7.call(Manager.java:403) at io.socket.parser.IOParser$Decoder.add(IOParser.java:105) at io.socket.client.Manager.ondata(Manager.java:419) at io.socket.client.Manager.access$1000(Manager.java:30) at io.socket.client.Manager$2.call(Manager.java:370) at io.socket.emitter.Emitter.emit(Emitter.java:117) at io.socket.engineio.client.Socket.onPacket(Socket.java:551) at io.socket.engineio.client.Socket.access$1000(Socket.java:36) at io.socket.engineio.client.Socket$5.call(Socket.java:335) at io.socket.emitter.Emitter.emit(Emitter.java:117) at io.socket.engineio.client.Transport.onPacket(Transport.java:126) at io.socket.engineio.client.Transport.onData(Transport.java:118) at io.socket.engineio.client.transports.WebSocket.access$100(WebSocket.java:24) at io.socket.engineio.client.transports.WebSocket$1$2.run(WebSocket.java:71) at io.socket.thread.EventThread$2.run(EventThread.java:80) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) at java.lang.Thread.run(Thread.java:919)

Using Socket Version 

implementation('io.socket:socket.io-client:1.0.0') {
        exclude group: 'org.json', module: 'json'
    }

**Comment by tushanFox** [comment]
Please attach your code.

**Comment by imransamed7** [comment]
Fix for this ?
